;;; hermeneus-storage.el --- -*- lexical-binding: t -*-

;; [[id:TKR:76751cd5-569d-483b-a6e0-2050e9760bd7][Dependencies:1]]
(require 'eieio)
(require 'eieio-base)
(require 'cl-generic)

(declare-function #'hermeneus-scan-entries "hermeneus-xml")
;; Dependencies:1 ends here

;; [[id:TKR:cc2d39d7-8b0f-4f8c-adfb-0d5e8d715cfd][Variables:1]]
(defvar hermeneus-storage-file (concat "lsj-cache" (when (executable-find "gzip") ".gz")))
(defvar hermeneus-storage-path nil) ; this is set by the setter function below

(defcustom hermeneus-storage-dir (expand-file-name "var/hermeneus" user-emacs-directory)
  "Directory in which to store files generated by Hermeneus.
At present, this means where to store the Hermeneus lexicon cache. If
you set this outside Customize, ensure that the directory
exists (creating it if necessary), and set ‘hermeneus-storage-path’ to
the value returned by calling ‘expand-file-name’ with two arguments: the
current value of ‘hermeneus-storage-file’, and the new value for
‘hermeneus-storage-dir’."
  :type 'directory
  :tag "Hermeneus — storage directory"
  :group 'hermeneus
  :set (lambda (symbol value)
         (unless (file-exists-p (directory-file-name value))
           (make-directory (directory-file-name value) t))
         (set-default symbol value)
         (setq hermeneus-storage-path
               (expand-file-name hermeneus-storage-file value))))
;; Variables:1 ends here

;; [[id:TKR:ec258183-0deb-4581-a0df-7ad3eec2dcd8][Objects:1]]
(defclass hermeneus-word ()
  ((key :type string
        :initarg :key
        :initform "")
   (id :type integer
       :initarg :id
       :initform 0)
   (loc :type (or cons null)
        :initarg :loc
        :initform nil))
  :documentation "A Hermeneus object to represent one word.")

(defclass hermeneus-lexicon (eieio-persistent)
  ((initialized :type (or boolean integer)
                :initarg :initialized
                :initform nil
                :documentation "Whether the lexicon object has been initialized, and (possibly) when.
Nil (the default) means uninitialized, t means initialized at an unknown
time, and an integer means the Unix timestamp (in seconds) of the time
at which the lexicon object was initialized.")
   ;; TODO that leaves the year 2038 problem for 32-bit systems, agh
   (entries :type hash-table
            :initarg :entries
            :initform (make-hash-table :size 116493 :test 'equal))
   ;; I have absolutely zero clue why
   ;; (file :initform hermeneus-storage-path) results in an
   ;; “invalid-slot-type” error, but this doesn’t:
   (file :initform (symbol-value 'hermeneus-storage-path))
   (file-header-line :initform ";; Hermeneus lexicon object"))
  :documentation "A Hermeneus object to represent a lexicon of words.
Use the function ‘hermeneus-get-entries’ to access the ‘entries’ slot.")
;; Objects:1 ends here

;; [[id:TKR:155090bb-4267-4ec2-be28-e402000a0a0e][Methods:1]]
(cl-defmethod make-instance ((cls (subclass hermeneus-lexicon)) &rest slots)
  "When making a ‘hermeneus-lexicon’ object, try to read it from a file.
(The file’s path can be passed as a “:file” keyword argument, but
otherwise defaults to ‘hermeneus-storage-path’.) If the file doesn’t
exist, or otherwise can’t be used, move on."
  (let ((path (or (plist-get slots :file)
                  hermeneus-storage-path)))
    (or (and (file-exists-p path)
             (eieio-persistent-read path cls t))
        (cl-call-next-method))))

(defvar hermeneus-lsj (hermeneus-lexicon nil))
;; Methods:1 ends here

(provide 'hermeneus-storage)

;;; hermeneus-storage.el ends here
