;;; hermeneus-storage.el --- -*- lexical-binding: t -*-

(require 'eieio)
(require 'eieio-base)
(require 'cl-generic)

(declare-function #'hermeneus-scan-entries "hermeneus-xml")

(defvar hermeneus-storage-file (concat "lsj-cache" (when (executable-find "gzip") ".gz")))
(defvar hermeneus-storage-path nil) ; this is set by the setter function below

(defcustom hermeneus-storage-dir (expand-file-name "var/hermeneus" user-emacs-directory)
  "Directory in which to store files generated by Hermeneus.
At present, this means where to store the Hermeneus lexicon cache. If
you set this outside Customize, ensure that the directory
exists (creating it if necessary), and set ‘hermeneus-storage-path’ to
the value returned by calling ‘expand-file-name’ with two arguments: the
current value of ‘hermeneus-storage-file’, and the new value for
‘hermeneus-storage-dir’."
  :type 'directory
  :tag "Hermeneus — storage directory"
  :group 'hermeneus
  :set (lambda (symbol value)
         (unless (file-exists-p (directory-file-name value))
           (make-directory (directory-file-name value) t))
         (set-default symbol value)
         (setq hermeneus-storage-path
               (expand-file-name hermeneus-storage-file value))))

(defclass hermeneus-word ()
  ((key :type string
        :initarg :key
        :initform "")
   (id :type integer
       :initarg :id
       :initform 0)
   (loc :type (or cons null)
        :initarg :loc
        :initform nil))
  :documentation "A Hermeneus object to represent one word.")

(defclass hermeneus-lexicon (eieio-persistent)
  ((initialized-p :type boolean
                  :initarg :initialized-p
                  :initform nil)
   (entries :type hash-table
            :initarg :entries
            :initform (make-hash-table :size 116493 :test 'equal))
   ;; I have absolutely zero clue why
   ;; (file :initform hermeneus-storage-path) results in an
   ;; “invalid-slot-type” error, but this doesn’t:
   (file :initform (symbol-value 'hermeneus-storage-path))
   (file-header-line :initform ";; Hermeneus lexicon object"))
  :documentation "A Hermeneus object to represent a lexicon of words.
Use the function ‘hermeneus-get-entries’ to access the ‘entries’ slot.")

(cl-defmethod make-instance ((cls (subclass hermeneus-lexicon)) &rest slots)
  "When making a ‘hermeneus-lexicon’ object, try to read it from a file.
(The file’s path can be passed as a “:file” keyword argument, but
otherwise defaults to ‘hermeneus-storage-path’.) If the file doesn’t
exist, or otherwise can’t be used, move on."
  (let ((path (or (plist-get slots :file)
                  hermeneus-storage-path)))
    (or (and (file-exists-p path)
             (eieio-persistent-read path cls t))
        (cl-call-next-method))))

(defvar hermeneus-lsj (hermeneus-lexicon nil))

(provide 'hermeneus-storage)

;;; hermeneus-storage.el ends here
