(defvar hrm-author-abbr-hash
#s(hash-table size 1095 test equal rehash-size 1.5 rehash-threshold 0.8125 data
("Abyd." "Abydenus" "Acerat." "Aceratus" "Acesand." "Acesander"
 "Achae." "Achaeus" "Ach.Tat." "Achilles Tatius" "Acus." "Acusilaus"
 "Adam." "Adamantius" "Ael." "Aelianus" "Ael.Dion." "Aelius Dionysius"
 "Aemil." "Aemilianus" "Aen.Gaz." "Aeneas Gazaeus" "Aen.Tact."
 "Aeneas Tacticus" "Aesar." "Aesara" "Aeschin." "Aeschines"
 "Aeschin.Socr." "Aeschines Socraticus" "A." "Aeschylus" "Aesch.Alex."
 "Aeschylus Alexandrinus" "Aesop." "Aesopus" "Aët." "Aëtius" "Afric."
 "Africanus, Julius" "Agaclyt." "Agaclytus" "Agatharch."
 "Agatharchides" "Agathem." "Agathemerus" "Agath." "Agathias"
 "Agathin." "Agathinus" "Agathocl." "Agathocles" "Alb." "Albinus"
 "Alc.Com." "Alcaeus" "Alc." "Alcaeus (Lyricus)" "Alc.Mess."
 "Alcaeus Messenius" "Alcid." "Alcidamas" "Alcin." "Alcinous"
 "Alciphr." "Alciphro" "Alcm." "Alcman" "Alexand.Com." "Alexander"
 "Alex.Aet." "Alexander Aetolus" "Alex.Aphr."
 "Alexander Aphrodisiensis" "Alex.Eph." "Alexander Ephesius"
 "Alex.Polyh." "Alexander Polyhistor" "Alex." "Alexis" "Alex.Trall."
 "Alexander Trallianus" "Alph." "Alpheus" "Alyp." "Alypius" "Amips."
 "Amipsias" "Ammian." "Ammianus" "Amm.Marc." "Ammianus Marcellinus"
 "Ammon." "Ammonius" "Anach." "Anacharsis" "Anacr." "Anacreon" "Anan."
 "Ananius" "Anaxag." "Anaxagoras" "Anaxandr." "Anaxandrides"
 "Anaxandr.Hist." "Anaxandrides (Historicus)" "Anaxarch." "Anaxarchus"
 "Anaxil." "Anaxilas" "Anaximand.Hist." "Anaximander" "Anaximand."
 "Anaximander (Philosophus)" "Anaximen." "Anaximenes" "Anaxipp."
 "Anaxippus" "And." "Andocides" "Androm." "Andromachus" "Andronic."
 "Andronicus" "Andronic.Rhod." "Andronicus Rhodius" "Androt."
 "Androtion" "Anon.Lond." "Anonymus Londnensis" "Anon.Rhythm."
 "Anonymus Rhythmicus" "Anon.Vat." "Anonymus Vaticanus" "Antag."
 "Antagoras" "Anthem." "Anthemius" "Anticl." "Anticlides" "Antid."
 "Antidotus" "Antig." "Antigonus Carystius" "Antig.Nic."
 "Antigonus Nicaeanus" "Antim." "Antimachus Colophonius"
 "Antioch.Astr." "Antiochus Atheniensis" "Antioch." "Antiochus"
 "Antioch.Hist." "Antiochus (Historicus)" "Antip.Sid."
 "Antipater Sidonius" "Antip.Thess." "Antipater Thessalonicensis"
 "Antiph." "Antiphanes" "Antiphan." "Antiphanes Megalopolitanus"
 "Antiphil." "Antiphilus" "Antipho Soph." "Antipho Sophista"
 "Antipho Trag." "Antipho" "Antisth." "Antisthenes" "Antist."
 "Antistius" "Ant.Lib." "Antoninus Liberalis" "Anton.Arg."
 "Antonius Argivus" "Ant.Diog." "Antonius Diogenes" "Antyll."
 "Antyllus" "Anub." "Anubion" "Anyt." "Anyte" "Aphth." "Aphthonius"
 "Apollinar." "Apollinarius" "Apollod.Com." "Apollodorus"
 "Apollod.Car." "Apollodorus Carystius" "Apollod.Gel."
 "Apollodorus Gelous" "Apollod." "Apollodorus Damascenus"
 "Apollod.Lyr." "Apollodorus (Lyricus)" "Apollonid." "Apollonides"
 "Apollonid.Trag." "Apollonides (Tragicus)" "Apollon." "Apollonius"
 "Apollon.Cit." "Apollonius Citiensis" "A.D." "Apollonius Dyscolus"
 "Apollon.Perg." "Apollonius Pergaeus" "A.R." "Apollonius Rhodius"
 "Ap.Ty." "Apollonius Tyanensis" "Apolloph." "Apollophanes" "Apostol."
 "Apostolius" "App." "Appianus" "Aps." "Apsines" "Apul." "Apuleius"
 "Aq." "Aquila" "Arab." "Arabius" "Arar." "Araros" "Arat." "Aratus"
 "Arc." "Arcadius" "Arcesil." "Arcesilaus" "Arched." "Archedicus"
 "Archemach." "Archemachus" "Archestr." "Archestratus" "Arch."
 "Archias" "Arch.Jun." "Archias Junior" "Archig." "Archigenes"
 "Archil." "Archilochus" "Archim." "Archimedes" "Archimel."
 "Archimelus" "Archipp." "Archippus" "Archyt.Amph."
 "Archytas Amphissensis" "Archyt." "Archytas Tarentinus" "Aret."
 "Aretaeus" "Aristaenet." "Aristaenetus" "Aristag." "Aristagoras"
 "Aristag.Hist." "Aristagoras (Historicus)" "Aristarch." "Aristarchus"
 "Aristarch.Sam." "Aristarchus Samius" "Aristarch.Trag."
 "Aristarchus (Tragicus)" "Aristeas Epic." "Aristeas" "Aristid."
 "Aristides" "Aristid.Mil." "Aristides Milesius" "Aristid.Quint."
 "Aristides Quintilianus" "Aristipp." "Aristippus" "Aristobul."
 "Aristobulus" "Aristocl." "Aristocles" "Aristocl.Hist."
 "Aristocles (Historicus)" "Aristodem." "Aristodemus" "Aristodic."
 "Aristodicus" "Aristomen." "Aristomenes" "Aristonym." "Aristonymus"
 "Ar." "Aristophanes" "Aristoph.Boeot." "Aristophanes Boeotus"
 "Ar.Byz." "Aristophanes Byzantinus" "Arist." "Aristoteles" "Aristox."
 "Aristoxenus" "Ar.Did." "Arius Didymus" "Arr." "Arrianus" "Artem."
 "Artemidorus Daldianus" "Artemid." "Artemidorus Tarsensis"
 "Arus.Mess." "Arusianus Messius" "Asclep." "Asclepiades Prusensis"
 "Asclep.Jun." "Asclepiades Junior" "Asclep.Myrl."
 "Asclepiades Myrleanus" "Asclep.Tragil." "Asclepiades Tragilensis"
 "Ascl." "Asclepius" "Asp." "Aspasius" "Astramps." "Astrampsychus"
 "Astyd." "Astydamas" "Ath." "Athenaeus" "Ath.Mech."
 "Athenaeus (Mechanicus)" "Ath.Med." "Athenaeus (Medicus)"
 "Athenodor.Tars." "Athenodorus Tarsensis" "Atil.Fort."
 "Atilius Fortunatianus" "Attal." "Attalus" "Attic." "Atticus" "Aus."
 "Ausonius" "Autocr." "Autocrates" "Autol." "Autolycus" "Autom."
 "Automedon" "Axionic." "Axionicus" "Axiop." "Axiopistus" "Babr."
 "Babrius" "Bacch." "Bacchius" "B." "Bacchylides" "Balbill."
 "Balbilla" "Barb." "Barbucallos" "Bass." "Bassus, Lollius"
 "Bato Sinop." "Bato Sinopensis" "Batr." "Batrachomyomachia" "Beros."
 "Berosus" "Besant." "Besantinus" "Blaes." "Blaesus" "Boeth."
 "Boethus" "Brut." "Brutus" "Buther." "Butherus" "Cael.Aur."
 "Caelius Aurelianus" "Call." "Callimachus" "Call.Com."
 "Callias (Comicus)" "Call.Hist." "Callias (Historicus)" "Callicrat."
 "Callicratidas" "Callinic.Rh." "Callinicus" "Callin." "Callinus"
 "Callistr.Hist." "Callistratus" "Callistr." "Callistratus (Sophista)"
 "Callix." "Callixinus" "Canthar." "Cantharus" "Carc." "Carcinus"
 "Carneisc." "Carneiscus" "Carph." "Carphyllides" "Caryst."
 "Carystius" "Cass." "Cassius" "Cass.Fel." "Cassius Felix" "Ceb."
 "Cebes" "Cels." "Celsus" "Cephisod." "Cephisodorus" "Cerc."
 "Cercidas" "Cercop." "Cercopes" "Cereal." "Cerealius" "Certamen"
 "Certamen Homeri et Hesiodi" "Chaerem.Hist." "Chaeremon" "Chaerem."
 "Chaeremon (Tragicus)" "Chamael." "Chamaeleon" "Chares Iamb."
 "Chares" "Chares Trag." "Chares (Tragicus)" "Chariclid."
 "Chariclides" "Charis." "Charisius" "Charixen." "Charixenes"
 "Charond." "Charondas" "Chionid." "Chionides" "Choeril." "Choerilus"
 "Choeril.Trag." "Choerilus (Tragicus)" "Choerob." "Choeroboscus"
 "Chor." "Choricius" "Chrysipp. Tyan." "Chrysippus Tyanensis" "Cic."
 "Cicero, M. Tullius" "Claudian." "Claudianus" "Claud.Iol."
 "Claudius Iolaus" "Cleaenet." "Cleaenetus" "Clearch.Com." "Clearchus"
 "Clearch." "Clearchus (Historicus)" "Clem.Al." "Clemens Alexandrinus"
 "Cleobul." "Cleobulus" "Cleom." "Cleomedes" "Cleon Sic."
 "Cleon Siculus" "Cleonid." "Cleonides" "Cleostrat." "Cleostratus"
 "Clin." "Clinias" "Clitarch." "Clitarchus" "Clitom." "Clitomachus"
 "Colot." "Colotes" "Coluth." "Coluthus" "Corinn." "Corinna"
 "Corn.Long." "Cornelius Longus" "Corn." "Cornutus" "Crater."
 "Craterus" "Crates Com." "Crates" "Crates Hist."
 "Crates (Historicus)" "Crates Theb." "Crates Thebanus" "Cratin."
 "Cratinus" "Cratin.Jun." "Cratinus Junior" "Cratipp." "Cratippus"
 "Crin." "Crinagoras" "Critias" "Critias" "Crito Com." "Crito"
 "Crobyl." "Crobylus" "Ctes." "Ctesias" "Cyllen." "Cyllenius" "Cyran."
 "Cyranus" "Cypr." "Cypria" "Cyr." "Cyrilli Glossarium" "Cyrill."
 "Cyrillus" "Damag." "Damagetus" "Dam." "Damascius" "Damian."
 "Damianus" "Damoch." "Damocharis" "Damocr." "Damocrates" "Damocrit."
 "Damocritus" "Damostr." "Damostratus" "Damox." "Damoxenus" "Deioch."
 "Deiochus" "Demad." "Demades" "Demetr."
 "Demetrius Phalereus (Rhetor)" "Demetr.Com.Nov."
 "Demetrius (Comicus Novae Comoediae)" "Demetr.Com.Vet."
 "Demetrius (Comicus Veteris Comoediae)" "Demetr.Apam."
 "Demetrius Apamensis" "Demetr.Lac." "Demetrius Lacon" "Dem.Phal."
 "Demetrius Phalereus" "Demetr.Troez." "Demetrius Troezenius"
 "Democh." "Demochares" "Democr." "Democritus" "Ps.-Democr."
 "Pseudo-Democritus" "Democr.Eph." "Democritus Ephesius" "Demod."
 "Demodocus" "Demonic." "Demonicus" "Demoph." "Demophilus" "D."
 "Demosthenes" "Dem.Bith." "Demosthenes Bithynus" "Dem.Ophth."
 "Demosthenes Ophthalmicus" "Dercyl." "Dercylus" "Dexipp." "Dexippus"
 "Diagor." "Diagoras" "Dicaearch." "Dicaearchus" "Dicaearch.Hist."
 "Dicaearchus (Historicus)" "Dicaeog." "Dicaeogenes" "Did." "Didymus"
 "Dieuch." "Dieuches" "Dieuchid." "Dieuchidas" "Din." "Dinarchus"
 "Dinol." "Dinolochus" "D.C." "Dio Cassius" "D.Chr."
 "Dio Chrysostomus" "Diocl." "Diocles" "Diocl.Com."
 "Diocles (Comicus)" "Diod.Com." "Diodorus" "Diod."
 "Diodorus (Epigrammaticus)" "Diod.Rh." "Diodorus (Rhetor)"
 "Diod.Ath." "Diodorus Atheniensis" "D.S." "Diodorus Siculus"
 "Diod.Tars." "Diodorus Tarsensis" "Diog.Apoll."
 "Diogenes Apolloniates" "Diog.Ath." "Diogenes Atheniensis" "Diog."
 "Diogenes Cynicus" "D.L." "Diogenes Laertius" "Diog.Oen."
 "Diogenes Oenoandensis" "Diog.Sinop." "Diogenes Sinopensis"
 "Diogenian." "Diogenianus" "Diogenian.Epicur."
 "Diogenianus Epicureus" "Diom." "Diomedes" "Dionys.Com." "Dionysius"
 "Dionys." "Dionysius (Rerum Naturalium Scriptor)" "Dionys.Trag."
 "Dionysius (Tragicus)" "Dion.Byz." "Dionysius Byzantius"
 "Dion.Calliph." "Dionysius Calliphontis filius" "Dionys.Eleg."
 "Dionysius Chalcus" "D.H." "Dionysius Halicarnassensis"
 "Dionys.Minor" "Dionysius Minor" "D.P." "Dionysius Periegeta"
 "Dionys.Sam." "Dionysius Samius" "D.T." "Dionysius Thrax" "Diophan."
 "Diophanes" "Dioph." "Diophantus" "Diosc." "Dioscorides"
 "Diosc.Hist." "Dioscorides (Historicus)" "Dsc."
 "Dioscorides (Dioscurides)" "Diosc.Gloss." "Dioscorides Glossator"
 "Diotim." "Diotimus" "Diotog." "Diotogenes" "Diox." "Dioxippus"
 "Diph." "Diphilus" "Diph.Siph." "Diphilus Siphnius" "Diyll."
 "Diyllus" "Donat." "Donatus, Aelius" "Doroth." "Dorotheus" "Dosiad."
 "Dosiadas" "Dosiad.Hist." "Dosiades" "Dosith." "Dositheus"
 "Ecphantid." "Ecphantides" "Ecphant." "Ecphantus" "Emp." "Empedocles"
 "Ephipp." "Ephippus" "Ephor." "Ephorus" "Epich." "Epicharmus"
 "Epicr." "Epicrates" "Epict." "Epictetus" "Epicur." "Epicurus"
 "Epig." "Epigonus" "Epil." "Epilycus" "Epimenid." "Epimenides"
 "Epin." "Epinicus" "Erasistr." "Erasistratus" "Eratosth."
 "Eratosthenes Scholasticus" "Erinn." "Erinna" "Eriph." "Eriphus"
 "Erot." "Erotianus" "Eryc." "Erycius" "Etrusc." "Etruscus" "Euang."
 "Euangelus" "Eubulid." "Eubulides" "Eub." "Eubulus" "Euc." "Euclides"
 "Eucrat." "Eucrates" "Eudem." "Eudemus" "Eudox." "Eudoxus"
 "Eudox.Com." "Eudoxus (Comicus)" "Eumel." "Eumelus" "Eun." "Eunapius"
 "Eunic." "Eunicus" "Euod." "Euodus" "Euph." "Euphorio" "Euphron."
 "Euphronius" "Eup." "Eupolis" "E." "Euripides" "Euryph." "Euryphamus"
 "Eus.Hist." "Eusebius" "Eus." "Eusebius Caesariensis" "Eus.Mynd."
 "Eusebius Myndius" "Eust." "Eustathius" "Eust.Epiph."
 "Eustathius Epiphaniensis" "Eustr." "Eustratius" "Euthycl."
 "Euthycles" "Eutoc." "Eutocius" "Eutolm." "Eutolmius" "Eutych."
 "Eutychianus" "Even." "Evenus" "Ezek." "Ezekiel" "Favorin."
 "Favorinus" "Fest." "Festus" "Firm." "Firmicus Maternus" "Gabriel."
 "Gabrielius" "Gaet." "Gaetulicus, Cn. Lentulus" "Gal." "Galenus"
 "Gell." "Gellius, Aulus" "Gem." "Geminus" "Germ." "Germanicus Caesar"
 "Glauc." "Glaucus Nicopolitanus" "Gorg." "Gorgias" "Greg.Cor."
 "Gregorius Corinthius" "Greg.Cypr." "Gregorius Cyprius" "Hadr.Rh."
 "Hadrianus" "Hadr." "Hadrianus Imperator" "Harmod." "Harmodius"
 "Harp." "Harpocratio" "Harp.Astr."
 "Harpocratio (Medicus et Astrologus)" "Hecat.Abd."
 "Hecataeus Abderita" "Hecat." "Hecataeus Milesius" "Hedyl." "Hedylus"
 "Hegem." "Hegemon" "Hegesand." "Hegesander" "Hegesian." "Hegesianax"
 "Hegesipp.Com." "Hegesippus" "Hegesipp."
 "Hegesippus (Epigrammaticus)" "Hld." "Heliodorus" "Heliod."
 "Heliodorus (Philosophus)" "Heliod.Hist." "Heliodorus (Periegeta)"
 "Hellad." "Helladius" "Hellanic." "Hellanicus" "Henioch." "Heniochus"
 "Heph.Astr." "Hephaestio" "Heph." "Hephaestio (Grammaticus)"
 "Heracl." "Heraclas" "Heraclid.Com." "Heraclides" "Heraclid."
 "Heraclides Tarentinus" "Heraclid.Cum." "Heraclides Cumaeus"
 "Heraclid.Lemb." "Heraclides Lembus" "Heraclid.Pont."
 "Heraclides Ponticus" "Heraclid.Sinop." "Heraclides Sinopensis"
 "Heraclit." "Heraclitus" "Herm." "Hermias Alexandrinus" "Hermesian."
 "Hermesianax" "Herm.Hist." "Hermias" "Herm.Iamb."
 "Hermias (Iambographus)" "Hermipp." "Hermippus" "Hermipp.Hist."
 "Hermippus (Historicus)" "Hermocl." "Hermocles" "Hermocr."
 "Hermocreon" "Hermod." "Hermodorus" "Hermog." "Hermogenes" "Herod."
 "Herodas" "Hdn." "Herodianus" "Herodor." "Herodorus" "Hdt."
 "Herodotus" "Herod.Med." "Herodotus (Medicus)" "Herophil."
 "Herophilus" "Hes." "Hesiodus" "Hsch.Mil." "Hesychius Milesius"
 "Hsch." "Hesychius" "Hices." "Hicesius" "Hierocl."
 "Hierocles Stoicus" "Hierocl.Hist." "Hierocles (Historicus)"
 "Hieronym.Hist." "Hieronymus Cardianus" "Him." "Himerius" "Hipparch."
 "Hipparchus" "Hipparch.Com." "Hipparchus (Comicus)" "Hippias Erythr."
 "Hippias Erythraeus" "Hp." "Hippocrates" "Hippod." "Hippodamus"
 "Hippol." "Hippolytus" "Hippon." "Hipponax" "Hom." "Homerus"
 "Honest." "Honestus" "Horap." "Horapollo" "Hyp." "Hyperides"
 "Hypsicl." "Hypsicles" "Iamb." "Iamblichus" "Ibyc." "Ibycus" "Il."
 "Ilias" "Il.Parv." "Ilias Parva" "Il.Pers." "Iliu Persis" "Iren."
 "Irenaeus" "Is." "Isaeus" "Isid.Trag." "Isidorus" "Isid.Aeg."
 "Isidorus Aegeates" "Isid.Char." "Isidorus Characenus" "Isid."
 "Isidorus Scholasticus" "Isig." "Isigonus" "Isoc." "Isocrates"
 "Isyll." "Isyllus" "Jo.Alex. vel Jo.Gramm." "Joannes Alexandrinus"
 "Jo.Diac." "Joannes Diaconus" "Jo.Gaz." "Joannes Gazaeus" "J."
 "Josephus" "Jul." "Julianus Imperator" "Jul. vel Jul.Aegypt."
 "Julianus Aegyptius" "Jul.Laod." "Julianus Laodicensis" "Junc."
 "Juncus" "Just." "Justinianus" "Juv." "Juvenalis, D. Junius"
 "Lamprocl." "Lamprocles" "Leo Phil." "Leo Philosophus" "Leon."
 "Leonidas Alexandrinus" "Leonid." "Leonidas (Medicus)" "Leont."
 "Leontius" "Lesb.Gramm." "Lesbonax" "Lesb.Rh." "Lesbonax (Rhetor)"
 "Leucipp." "Leucippus" "Lib." "Libanius" "Licymn." "Licymnius"
 "Limen." "Limenius" "Loll." "Lollius Bassus" "Longin." "Longinus"
 "Luc." "Lucianus" "Lucill." "Lucillius" "Lyc." "Lycophron"
 "Lycophronid." "Lycophronides" "Lycurg." "Lycurgus" "Lyd."
 "Lydus, Joannes Laurentius" "Lync." "Lynceus" "Lys." "Lysias"
 "Lysimachid." "Lysimachides" "Lysim." "Lysimachus" "Lysipp."
 "Lysippus" "Macar." "Macarius" "Maced." "Macedonius Thessalonicensis"
 "Macr." "Macrobius" "Maec." "Maecius" "Magn." "Magnes" "Magnus Hist."
 "Magnus" "Maiist." "Maiistas" "Malch." "Malchus" "Mamerc." "Mamercus"
 "Man." "Manetho" "Man.Hist." "Manetho (Historicus)" "Marcellin."
 "Marcellinus" "Marc.Sid." "Marcellus Sidetes" "Marcian." "Marcianus"
 "M.Ant." "Marcus Antoninus" "Marc.Arg." "Marcus Argentarius"
 "Maria Alch." "Maria" "Marian." "Marianus" "Marin." "Marinus"
 "Mar.Vict." "Marius Victorinus" "Mart." "Martialis" "Mart.Cap."
 "Martianus Capella" "Max." "Maximus" "Max.Tyr." "Maximus Tyrius"
 "Megasth." "Megasthenes" "Melamp." "Melampus" "Melanipp."
 "Melanippides" "Melanth.Hist." "Melanthius" "Melanth.Trag."
 "Melanthius (Tragicus)" "Mel." "Meleager" "Meliss." "Melissus"
 "Memn." "Memnon" "Menaechm." "Menaechmus" "Men." "Menander" "Men.Rh."
 "Menander (Rhetor)" "Men.Eph." "Menander Ephesius" "Men.Prot."
 "Menander Protector" "Menecl." "Menecles Barcaeus" "Menecr."
 "Menecrates" "Menecr.Eph." "Menecrates Ephesius" "Menecr.Xanth."
 "Menecrates Xanthius" "Menemach." "Menemachus" "Menesth."
 "Menesthenes" "Menipp." "Menippus" "Menodot." "Menodotus Samius"
 "Mesom." "Mesomedes" "Metag." "Metagenes" "Metrod." "Metrodorus"
 "Metrod.Chius" "Metrodorus Chius" "Metrod.Sceps."
 "Metrodorus Scepsius" "Mich." "Michael Ephesius" "Mimn." "Mimnermus"
 "Mimn.Trag." "Mimnermus (Tragicus)" "Minuc." "Minucianus" "Mithr."
 "Mithradates" "Mnasalc." "Mnasalcas" "Mnesim." "Mnesimachus"
 "Mnesith.Ath." "Mnesitheus Atheniensis" "Mnesith.Cyz."
 "Mnesitheus Cyzicenus" "Moer." "Moeris" "MoschioTrag." "Moschio"
 "Mosch." "Moschus" "Muc.Scaev." "Mucius Scaevola" "Mund."
 "Mundus Munatius" "Musae." "Musaeus" "Music." "Musicius" "Muson."
 "Musonius" "Myrin." "Myrinus" "Myrsil." "Myrsilus" "Myrtil."
 "Myrtilus" "Naumach." "Naumachius" "Nausicr." "Nausicrates"
 "Nausiph." "Nausiphanes" "Neanth." "Neanthes" "Nearch." "Nearchus"
 "Nech." "Nechepso" "Neophr." "Neophron" "Neoptol." "Neoptolemus"
 "Nicaenet." "Nicaenetus" "Nic." "Nicias" "Nicarch." "Nicarchus"
 "Nicoch." "Nicochares" "Nicocl." "Nicocles" "Nicod." "Nicodemus"
 "Nicol.Com." "Nicolaus" "Nicol." "Nicolaus (Rhetor)" "Nic.Dam."
 "Nicolaus Damascenus" "Nicom.Com." "Nicomachus" "Nicom.Trag."
 "Nicomachus (Tragicus)" "Nicom." "Nicomachus Gerasenus"
 "Nicostr.Com." "Nicostratus" "Nicostr." "Nicostratus (Philosophus)"
 "Nonn." "Nonnus" "Noss." "Nossis" "Numen." "Numenius Heracleota"
 "Nymphod." "Nymphodorus" "Ocell." "Ocellus Lucanus" "Od." "Odyssea"
 "Oenom." "Oenomaus" "Olymp.Alch." "Olympiodorus" "Olymp.Hist."
 "Olympiodorus (Historicus)" "Olymp." "Olympiodorus (Philosophus)"
 "Onat." "Onatas" "Onos." "Onosander (Onasander)" "Ophel." "Ophelio"
 "Opp." "Oppianus Apamensis" "Orib." "Oribasius" "Orph." "Orphica"
 "Palaeph." "Palaephatus" "Palch." "Palchus" "Pall." "Palladius"
 "Pamphil." "Pamphilus" "Pancrat." "Pancrates" "Panyas." "Panyasis"
 "Papp." "Pappus" "Parm." "Parmenides" "Parmen." "Parmenio" "Parrhas."
 "Parrhasius" "Parth." "Parthenius" "Patrocl." "Patrocles Thurius"
 "Paul.Aeg." "Paulus Aegineta" "Paul.Al." "Paulus Alexandrinus"
 "Paul.Sil." "Paulus Silentiarius" "Paus." "Pausanias" "Paus.Dam."
 "Pausanias Damascenus" "Paus.Gr." "Pausanias Grammaticus" "Pediasim."
 "Pediasimus" "Pelag.Alch." "Pelagius" "Pempel." "Pempelus" "Perict."
 "Perictione" "Pers." "Persius" "Petos." "Petosiris" "Petron."
 "Petronius" "Petr.Patr." "Petrus Patricius" "Phaedim." "Phaedimus"
 "Phaënn." "Phaënnus" "Phaest." "Phaestus" "Phal." "Phalaecus"
 "Phalar." "Phalaris" "Phan." "Phanias" "Phan.Hist."
 "Phanias (Historicus)" "Phanocl." "Phanocles" "Phanod." "Phanodemus"
 "Pherecr." "Pherecrates" "Pherecyd." "Pherecydes Lerius"
 "Pherecyd.Syr." "Pherecydes Syrius" "Philagr." "Philagrius" "Philem."
 "Philemo" "Philem.Jun." "Philemo Junior" "Philetaer." "Philetaerus"
 "Philippid." "Philippides" "Philipp.Com." "Philippus" "Phil."
 "Philippus (Epigrammaticus)" "Philisc.Com." "Philiscus"
 "Philisc.Trag." "Philiscus (Tragicus)" "Philist." "Philistus"
 "Ph.Epic." "Philo" "Ph." "Philo Judaeus" "Ph.Bybl." "Philo Byblius"
 "Ph.Byz." "Philo Byzantius" "Ph.Tars." "Philo Tarsensis" "Philoch."
 "Philochorus" "Philocl." "Philocles" "Philod.Scarph."
 "Philodamus Scarpheus" "Phld." "Philodemus Gadarensis" "Philol."
 "Philolaus" "Philomnest." "Philomnestus" "Philonid." "Philonides"
 "Phlp." "Philoponus, Joannes" "Philosteph.Com." "Philostephanus"
 "Philosteph.Hist." "Philostephanus (Historicus)" "Philostr."
 "Philostratus" "Philostr.Jun." "Philostratus Junior" "Philox."
 "Philoxenus" "Philox.Gramm." "Philoxenus (Grammaticus)" "Philum."
 "Philumenus" "Philyll." "Philyllius" "Phint." "Phintys" "Phleg."
 "Phlegon Trallianus" "Phoc." "Phocylides" "Phoeb." "Phoebammon"
 "Phoenicid." "Phoenicides" "Phoen." "Phoenix" "Phot." "Photius"
 "Phryn." "Phrynichus" "Phryn.Com." "Phrynichus (Comicus)"
 "Phryn.Trag." "Phrynichus (Tragicus)" "Phylarch." "Phylarchus"
 "Phylotim." "Phylotimus" "Pi." "Pindarus" "Pisand." "Pisander"
 "Pittac." "Pittacus" "Pl.Com." "Plato" "Pl." "Plato (Philosophus)"
 "Pl.Jun." "Plato Junior" "Platon." "Platonius" "Plaut." "Plautus"
 "Plin." "Plinius" "Plot." "Plotinus" "Plu." "Plutarchus"
 "Polem.Hist." "Polemo" "Polem." "Polemo Sophista" "Polioch."
 "Poliochus" "Poll." "Pollux" "Polyaen." "Polyaenus, Julius" "Plb."
 "Polybius" "Plb.Rh." "Polybius Sardianus" "Polycharm." "Polycharmus"
 "Polyclit." "Polyclitus" "Polycr." "Polycrates" "Polystr."
 "Polystratus" "Polyzel." "Polyzelus" "Pomp." "Pompeius" "Pomp.Mac."
 "Pompeius Macer" "Porph." "Porphyrius Tyrius" "Posidipp."
 "Posidippus" "Posidon." "Posidonius" "Pratin." "Pratinas" "Praxag."
 "Praxagoras" "Praxill." "Praxilla" "Priscian." "Priscianus"
 "Prisc.Lyd." "Priscianus Lydus" "Prisc." "Priscus" "Procl." "Proclus"
 "Procop." "Procopius Caesariensis" "Procop.Gaz." "Procopius Gazaeus"
 "Prodic." "Prodicus" "Promathid." "Promathidas" "Protag."
 "Protagoras" "Protagorid." "Protagoridas" "Proxen." "Proxenus"
 "Ps.-Callisth." "Pseudo-Callisthenes" "Ps.-Phoc." "Pseudo-Phocylidea"
 "Ptol." "Ptolemaeus" "Ptol.Ascal." "Ptolemaeus Ascalonita"
 "Ptol.Chenn." "Ptolemaeus Chennos" "Ptol.Euerg."
 "Ptolemaeus Euergetes II" "Ptol.Megalop."
 "Ptolemaeus Megalopolitanus" "Pythaen." "Pythaenetus" "Pythag."
 "Pythagoras" "Pythocl." "Pythocles" "Quint." "Quintilianus" "Q.S."
 "Quintus Smyrnaeus" "Rh." "Rhetores Graeci" "Rhetor." "Rhetorius"
 "Rhian." "Rhianus" "Rhinth." "Rhinthon" "Rufin." "Rufinus" "Ruf."
 "Rufus" "Ruf.Rh." "Rufus (Rhetor)" "Rutil." "Rutilius Lupus"
 "Tull.Sab." "Sabinus, Tullius" "Sacerd." "Sacerdos, Marius Plotius"
 "Sallust." "Sallustius" "Sannyr." "Sannyrio" "Sapph." "Sappho"
 "Satyr." "Satyrus" "Scyl." "Scylax" "Scymn." "Scymnus" "Scythin."
 "Scythinus Teius" "Secund." "Secundus" "Seleuc." "Seleucus"
 "Seleuc.Lyr." "Seleucus (Lyricus)" "Semon." "Semonides" "Seren."
 "Serenus" "Serv." "Servius" "Sever." "Severus" "Sext." "Sextus"
 "S.E." "Sextus Empiricus" "Silen." "Silenus" "Simon." "Simonides"
 "Simp." "Simplicius" "Simyl." "Simylus" "Socr.Arg."
 "Socrates Argivus" "Socr.Cous" "Socrates Cous" "Socr.Rhod."
 "Socrates Rhodius" "Socr." "Socratis et Socraticorum Epistulae"
 "Sol." "Solon" "Sopat." "Sopater" "Sopat.Rh." "Sopater (Rhetor)"
 "Sophil." "Sophilus" "S." "Sophocles" "Sophon" "Sophonias" "Sophr."
 "Sophron" "Sor." "Soranus" "Sosib." "Sosibius" "Sosicr." "Sosicrates"
 "Sosicr.Hist." "Sosicrates (Historicus)" "Sosicr.Rhod."
 "Sosicrates Rhodius" "Sosip." "Sosipater" "Sosiph." "Sosiphanes"
 "Sosith." "Sositheus" "Sostrat." "Sostratus" "Sosyl." "Sosylus"
 "Sotad.Com." "Sotades" "Sotad." "Sotades (Lyricus)" "Speus."
 "Speusippus" "Sphaer.Hist." "Sphaerus" "Staphyl." "Staphylus"
 "Stat.Flacc." "Statyllius Flaccus" "Steph.Com." "Stephanus" "Steph."
 "Stephanus (Philosophus)" "St.Byz." "Stephanus Byzantius" "Stesich."
 "Stesichorus" "Stesimbr." "Stesimbrotus" "Sthenid." "Sthenidas"
 "Stob." "Stobaeus, Joannes" "Str." "Strabo" "Strato Com." "Strato"
 "Strat." "Strato (Epigrammaticus)" "Stratt." "Strattis" "Suet."
 "Suetonius" "Suid." "Suidas" "Sulp.Max." "Sulpicius Maximus" "Sus."
 "Susario" "Sm." "Symmachus" "Syn.Alch." "Synesius" "Syrian."
 "Syrianus" "Telecl." "Teleclides" "Telesill." "Telesilla" "Telest."
 "Telestes" "Ter.Maur." "Terentianus Maurus" "Ter.Scaur."
 "Terentius Scaurus" "Terp." "Terpander" "Thal." "Thales" "Theaet."
 "Theaetetus" "Theagen." "Theagenes" "Theag." "Theages"
 "Themiso Hist." "Themiso" "Them." "Themistius" "Themist."
 "Themistocles" "Theocl." "Theocles" "Theoc." "Theocritus" "Theodect."
 "Theodectes" "Theodorid." "Theodoridas" "Theod." "Theodorus"
 "Theodos." "Theodosius Alexandrinus" "Thd." "Theodotion" "Theognet."
 "Theognetus" "Thgn." "Theognis" "Thgn.Trag." "Theognis (Tragicus)"
 "Thgn.Hist." "Theognis Rhodius" "Theognost." "Theognostus" "Theolyt."
 "Theolytus" "Theon Gymn." "Theon Gymnasiarcha" "Theo Sm."
 "Theon Smyrnaeus" "Theoph." "Theophanes" "Theophil." "Theophilus"
 "Thphr." "Theophrastus" "Theopomp.Com." "Theopompus" "Theopomp.Hist."
 "Theopompus (Historicus)" "Theopomp.Coloph." "Theopompus Colophonius"
 "Thom." "Thomas" "Thom.Mag." "Thomas Magister" "Thrasym."
 "Thrasymachus" "Th." "Thucydides" "Thugen." "Thugenides" "Thyill."
 "Thyillus" "Thymocl." "Thymocles" "Tib." "Tiberius" "Tib.Ill."
 "Tiberius Illustrius" "Tim." "Timotheus (Lyricus)" "Timae."
 "Timaeus (Historicus)" "Ti.Locr." "Timaeus Locrus" "Timag."
 "Timagenes" "Timocl." "Timocles" "Timocr." "Timocreon" "Timostr."
 "Timostratus" "Tim.Com." "Timotheus" "Tim.Gaz." "Timotheus Gazaeus"
 "Titanomach." "Titanomachia" "Trophil." "Trophilus" "Tryph."
 "Tryphiodorus" "Tull.Flacc." "Tullius Flaccus" "Tull.Gem."
 "Tullius Geminus" "Tull.Laur." "Tullius Laurea" "Tymn." "Tymnes"
 "Tyrt." "Tyrtaeus" "Tz." "Tzetzes, Joannes" "Ulp." "Ulpianus" "Uran."
 "Uranius" "Vel.Long." "Velius Longus" "Vett.Val." "Vettius Valens"
 "LXX" "Vetus Testamentum Graece redditum" "Vitr." "Vitruvius"
 "Xanth." "Xanthus" "Xenag." "Xenagoras" "Xenarch." "Xenarchus"
 "Xenocl." "Xenocles" "Xenocr." "Xenocrates" "Xenoph." "Xenophanes"
 "X." "Xenophon" "X.Eph." "Xenophon Ephesius" "Zaleuc." "Zaleucus"
 "Zelot." "Zelotus" "Zeno Eleat." "Zeno Eleaticus" "Zen." "Zenobius"
 "Zenod." "Zenodotus" "Zonae." "Zonaeus" "Zonar." "Zonaras" "Zon."
 "Zonas" "Zopyr.Hist." "Zopyrus" "Zopyr." "Zopyrus (Medicus)"
 "Zos.Alch." "Zosimus" "Zos." "Zosimus (Historicus)"))
  "A hash table containing every author abbreviation in the LSJ.")

(provide 'hrm-abbr)
