(defvar hrm-author-abbr-hash
#s(hash-table size 1095 test equal rehash-size 1.5 rehash-threshold 0.8125 data
("Abyd." "Abydenus" "Acerat." "Aceratus" "Acesand." "Acesander"
 "Achae." "Achaeus" "Ach.Tat." "Achilles Tatius" "Acus." "Acusilaus"
 "Adam." "Adamantius" "Ael." "Aelianus" "Ael.Dion." "Aelius Dionysius"
 "Aemil." "Aemilianus" "Aen.Gaz." "Aeneas Gazaeus" "Aen.Tact."
 "Aeneas Tacticus" "Aesar." "Aesara" "Aeschin." "Aeschines"
 "Aeschin.Socr." "Aeschines Socraticus" "A." "Aeschylus" "Aesch.Alex."
 "Aeschylus Alexandrinus" "Aesop." "Aesopus" "Aët." "Aëtius" "Afric."
 "Africanus, Julius" "Agaclyt." "Agaclytus" "Agatharch."
 "Agatharchides" "Agathem." "Agathemerus" "Agath." "Agathias"
 "Agathin." "Agathinus" "Agathocl." "Agathocles" "Alb." "Albinus"
 "Alc.Com." "Alcaeus" "Alc." "Alcaeus (Lyricus)" "Alc.Mess."
 "Alcaeus Messenius" "Alcid." "Alcidamas" "Alcin." "Alcinous"
 "Alciphr." "Alciphro" "Alcm." "Alcman" "Alexand.Com." "Alexander"
 "Alex.Aet." "Alexander Aetolus" "Alex.Aphr."
 "Alexander Aphrodisiensis" "Alex.Eph." "Alexander Ephesius"
 "Alex.Polyh." "Alexander Polyhistor" "Alex." "Alexis" "Alex.Trall."
 "Alexander Trallianus" "Alph." "Alpheus" "Alyp." "Alypius" "Amips."
 "Amipsias" "Ammian." "Ammianus" "Amm.Marc." "Ammianus Marcellinus"
 "Ammon." "Ammonius" "Anach." "Anacharsis" "Anacr." "Anacreon" "Anan."
 "Ananius" "Anaxag." "Anaxagoras" "Anaxandr." "Anaxandrides"
 "Anaxandr.Hist." "Anaxandrides (Historicus)" "Anaxarch." "Anaxarchus"
 "Anaxil." "Anaxilas" "Anaximand.Hist." "Anaximander" "Anaximand."
 "Anaximander (Philosophus)" "Anaximen." "Anaximenes" "Anaxipp."
 "Anaxippus" "And." "Andocides" "Androm." "Andromachus" "Andronic."
 "Andronicus" "Andronic.Rhod." "Andronicus Rhodius" "Androt."
 "Androtion" "Anon.Lond." "Anonymus Londnensis" "Anon.Rhythm."
 "Anonymus Rhythmicus" "Anon.Vat." "Anonymus Vaticanus" "Antag."
 "Antagoras" "Anthem." "Anthemius" "Anticl." "Anticlides" "Antid."
 "Antidotus" "Antig." "Antigonus Carystius" "Antig.Nic."
 "Antigonus Nicaeanus" "Antim." "Antimachus Colophonius"
 "Antioch.Astr." "Antiochus Atheniensis" "Antioch." "Antiochus"
 "Antioch.Hist." "Antiochus (Historicus)" "Antip.Sid."
 "Antipater Sidonius" "Antip.Thess." "Antipater Thessalonicensis"
 "Antiph." "Antiphanes" "Antiphan." "Antiphanes Megalopolitanus"
 "Antiphil." "Antiphilus" "Antipho Soph." "Antipho Sophista"
 "Antipho Trag." "Antipho" "Antisth." "Antisthenes" "Antist."
 "Antistius" "Ant.Lib." "Antoninus Liberalis" "Anton.Arg."
 "Antonius Argivus" "Ant.Diog." "Antonius Diogenes" "Antyll."
 "Antyllus" "Anub." "Anubion" "Anyt." "Anyte" "Aphth." "Aphthonius"
 "Apollinar." "Apollinarius" "Apollod.Com." "Apollodorus"
 "Apollod.Car." "Apollodorus Carystius" "Apollod.Gel."
 "Apollodorus Gelous" "Apollod." "Apollodorus Damascenus"
 "Apollod.Lyr." "Apollodorus (Lyricus)" "Apollonid." "Apollonides"
 "Apollonid.Trag." "Apollonides (Tragicus)" "Apollon." "Apollonius"
 "Apollon.Cit." "Apollonius Citiensis" "A.D." "Apollonius Dyscolus"
 "Apollon.Perg." "Apollonius Pergaeus" "A.R." "Apollonius Rhodius"
 "Ap.Ty." "Apollonius Tyanensis" "Apolloph." "Apollophanes" "Apostol."
 "Apostolius" "App." "Appianus" "Aps." "Apsines" "Apul." "Apuleius"
 "Aq." "Aquila" "Arab." "Arabius" "Arar." "Araros" "Arat." "Aratus"
 "Arc." "Arcadius" "Arcesil." "Arcesilaus" "Arched." "Archedicus"
 "Archemach." "Archemachus" "Archestr." "Archestratus" "Arch."
 "Archias" "Arch.Jun." "Archias Junior" "Archig." "Archigenes"
 "Archil." "Archilochus" "Archim." "Archimedes" "Archimel."
 "Archimelus" "Archipp." "Archippus" "Archyt.Amph."
 "Archytas Amphissensis" "Archyt." "Archytas Tarentinus" "Aret."
 "Aretaeus" "Aristaenet." "Aristaenetus" "Aristag." "Aristagoras"
 "Aristag.Hist." "Aristagoras (Historicus)" "Aristarch." "Aristarchus"
 "Aristarch.Sam." "Aristarchus Samius" "Aristarch.Trag."
 "Aristarchus (Tragicus)" "Aristeas Epic." "Aristeas" "Aristid."
 "Aristides" "Aristid.Mil." "Aristides Milesius" "Aristid.Quint."
 "Aristides Quintilianus" "Aristipp." "Aristippus" "Aristobul."
 "Aristobulus" "Aristocl." "Aristocles" "Aristocl.Hist."
 "Aristocles (Historicus)" "Aristodem." "Aristodemus" "Aristodic."
 "Aristodicus" "Aristomen." "Aristomenes" "Aristonym." "Aristonymus"
 "Ar." "Aristophanes" "Aristoph.Boeot." "Aristophanes Boeotus"
 "Ar.Byz." "Aristophanes Byzantinus" "Arist." "Aristoteles" "Aristox."
 "Aristoxenus" "Ar.Did." "Arius Didymus" "Arr." "Arrianus" "Artem."
 "Artemidorus Daldianus" "Artemid." "Artemidorus Tarsensis"
 "Arus.Mess." "Arusianus Messius" "Asclep." "Asclepiades Prusensis"
 "Asclep.Jun." "Asclepiades Junior" "Asclep.Myrl."
 "Asclepiades Myrleanus" "Asclep.Tragil." "Asclepiades Tragilensis"
 "Ascl." "Asclepius" "Asp." "Aspasius" "Astramps." "Astrampsychus"
 "Astyd." "Astydamas" "Ath." "Athenaeus" "Ath.Mech."
 "Athenaeus (Mechanicus)" "Ath.Med." "Athenaeus (Medicus)"
 "Athenodor.Tars." "Athenodorus Tarsensis" "Atil.Fort."
 "Atilius Fortunatianus" "Attal." "Attalus" "Attic." "Atticus" "Aus."
 "Ausonius" "Autocr." "Autocrates" "Autol." "Autolycus" "Autom."
 "Automedon" "Axionic." "Axionicus" "Axiop." "Axiopistus" "Babr."
 "Babrius" "Bacch." "Bacchius" "B." "Bacchylides" "Balbill."
 "Balbilla" "Barb." "Barbucallos" "Bass." "Bassus, Lollius"
 "Bato Sinop." "Bato Sinopensis" "Batr." "Batrachomyomachia" "Beros."
 "Berosus" "Besant." "Besantinus" "Blaes." "Blaesus" "Boeth."
 "Boethus" "Brut." "Brutus" "Buther." "Butherus" "Cael.Aur."
 "Caelius Aurelianus" "Call." "Callimachus" "Call.Com."
 "Callias (Comicus)" "Call.Hist." "Callias (Historicus)" "Callicrat."
 "Callicratidas" "Callinic.Rh." "Callinicus" "Callin." "Callinus"
 "Callistr.Hist." "Callistratus" "Callistr." "Callistratus (Sophista)"
 "Callix." "Callixinus" "Canthar." "Cantharus" "Carc." "Carcinus"
 "Carneisc." "Carneiscus" "Carph." "Carphyllides" "Caryst."
 "Carystius" "Cass." "Cassius" "Cass.Fel." "Cassius Felix" "Ceb."
 "Cebes" "Cels." "Celsus" "Cephisod." "Cephisodorus" "Cerc."
 "Cercidas" "Cercop." "Cercopes" "Cereal." "Cerealius" "Certamen"
 "Certamen Homeri et Hesiodi" "Chaerem.Hist." "Chaeremon" "Chaerem."
 "Chaeremon (Tragicus)" "Chamael." "Chamaeleon" "Chares Iamb."
 "Chares" "Chares Trag." "Chares (Tragicus)" "Chariclid."
 "Chariclides" "Charis." "Charisius" "Charixen." "Charixenes"
 "Charond." "Charondas" "Chionid." "Chionides" "Choeril." "Choerilus"
 "Choeril.Trag." "Choerilus (Tragicus)" "Choerob." "Choeroboscus"
 "Chor." "Choricius" "Chrysipp. Tyan." "Chrysippus Tyanensis" "Cic."
 "Cicero, M. Tullius" "Claudian." "Claudianus" "Claud.Iol."
 "Claudius Iolaus" "Cleaenet." "Cleaenetus" "Clearch.Com." "Clearchus"
 "Clearch." "Clearchus (Historicus)" "Clem.Al." "Clemens Alexandrinus"
 "Cleobul." "Cleobulus" "Cleom." "Cleomedes" "Cleon Sic."
 "Cleon Siculus" "Cleonid." "Cleonides" "Cleostrat." "Cleostratus"
 "Clin." "Clinias" "Clitarch." "Clitarchus" "Clitom." "Clitomachus"
 "Colot." "Colotes" "Coluth." "Coluthus" "Corinn." "Corinna"
 "Corn.Long." "Cornelius Longus" "Corn." "Cornutus" "Crater."
 "Craterus" "Crates Com." "Crates" "Crates Hist."
 "Crates (Historicus)" "Crates Theb." "Crates Thebanus" "Cratin."
 "Cratinus" "Cratin.Jun." "Cratinus Junior" "Cratipp." "Cratippus"
 "Crin." "Crinagoras" "Critias" "Critias" "Crito Com." "Crito"
 "Crobyl." "Crobylus" "Ctes." "Ctesias" "Cyllen." "Cyllenius" "Cyran."
 "Cyranus" "Cypr." "Cypria" "Cyr." "Cyrilli Glossarium" "Cyrill."
 "Cyrillus" "Damag." "Damagetus" "Dam." "Damascius" "Damian."
 "Damianus" "Damoch." "Damocharis" "Damocr." "Damocrates" "Damocrit."
 "Damocritus" "Damostr." "Damostratus" "Damox." "Damoxenus" "Deioch."
 "Deiochus" "Demad." "Demades" "Demetr."
 "Demetrius Phalereus (Rhetor)" "Demetr.Com.Nov."
 "Demetrius (Comicus Novae Comoediae)" "Demetr.Com.Vet."
 "Demetrius (Comicus Veteris Comoediae)" "Demetr.Apam."
 "Demetrius Apamensis" "Demetr.Lac." "Demetrius Lacon" "Dem.Phal."
 "Demetrius Phalereus" "Demetr.Troez." "Demetrius Troezenius"
 "Democh." "Demochares" "Democr." "Democritus" "Ps.-Democr."
 "Pseudo-Democritus" "Democr.Eph." "Democritus Ephesius" "Demod."
 "Demodocus" "Demonic." "Demonicus" "Demoph." "Demophilus" "D."
 "Demosthenes" "Dem.Bith." "Demosthenes Bithynus" "Dem.Ophth."
 "Demosthenes Ophthalmicus" "Dercyl." "Dercylus" "Dexipp." "Dexippus"
 "Diagor." "Diagoras" "Dicaearch." "Dicaearchus" "Dicaearch.Hist."
 "Dicaearchus (Historicus)" "Dicaeog." "Dicaeogenes" "Did." "Didymus"
 "Dieuch." "Dieuches" "Dieuchid." "Dieuchidas" "Din." "Dinarchus"
 "Dinol." "Dinolochus" "D.C." "Dio Cassius" "D.Chr."
 "Dio Chrysostomus" "Diocl." "Diocles" "Diocl.Com."
 "Diocles (Comicus)" "Diod.Com." "Diodorus" "Diod."
 "Diodorus (Epigrammaticus)" "Diod.Rh." "Diodorus (Rhetor)"
 "Diod.Ath." "Diodorus Atheniensis" "D.S." "Diodorus Siculus"
 "Diod.Tars." "Diodorus Tarsensis" "Diog.Apoll."
 "Diogenes Apolloniates" "Diog.Ath." "Diogenes Atheniensis" "Diog."
 "Diogenes Cynicus" "D.L." "Diogenes Laertius" "Diog.Oen."
 "Diogenes Oenoandensis" "Diog.Sinop." "Diogenes Sinopensis"
 "Diogenian." "Diogenianus" "Diogenian.Epicur."
 "Diogenianus Epicureus" "Diom." "Diomedes" "Dionys.Com." "Dionysius"
 "Dionys." "Dionysius (Rerum Naturalium Scriptor)" "Dionys.Trag."
 "Dionysius (Tragicus)" "Dion.Byz." "Dionysius Byzantius"
 "Dion.Calliph." "Dionysius Calliphontis filius" "Dionys.Eleg."
 "Dionysius Chalcus" "D.H." "Dionysius Halicarnassensis"
 "Dionys.Minor" "Dionysius Minor" "D.P." "Dionysius Periegeta"
 "Dionys.Sam." "Dionysius Samius" "D.T." "Dionysius Thrax" "Diophan."
 "Diophanes" "Dioph." "Diophantus" "Diosc." "Dioscorides"
 "Diosc.Hist." "Dioscorides (Historicus)" "Dsc."
 "Dioscorides (Dioscurides)" "Diosc.Gloss." "Dioscorides Glossator"
 "Diotim." "Diotimus" "Diotog." "Diotogenes" "Diox." "Dioxippus"
 "Diph." "Diphilus" "Diph.Siph." "Diphilus Siphnius" "Diyll."
 "Diyllus" "Donat." "Donatus, Aelius" "Doroth." "Dorotheus" "Dosiad."
 "Dosiadas" "Dosiad.Hist." "Dosiades" "Dosith." "Dositheus"
 "Ecphantid." "Ecphantides" "Ecphant." "Ecphantus" "Emp." "Empedocles"
 "Ephipp." "Ephippus" "Ephor." "Ephorus" "Epich." "Epicharmus"
 "Epicr." "Epicrates" "Epict." "Epictetus" "Epicur." "Epicurus"
 "Epig." "Epigonus" "Epil." "Epilycus" "Epimenid." "Epimenides"
 "Epin." "Epinicus" "Erasistr." "Erasistratus" "Eratosth."
 "Eratosthenes Scholasticus" "Erinn." "Erinna" "Eriph." "Eriphus"
 "Erot." "Erotianus" "Eryc." "Erycius" "Etrusc." "Etruscus" "Euang."
 "Euangelus" "Eubulid." "Eubulides" "Eub." "Eubulus" "Euc." "Euclides"
 "Eucrat." "Eucrates" "Eudem." "Eudemus" "Eudox." "Eudoxus"
 "Eudox.Com." "Eudoxus (Comicus)" "Eumel." "Eumelus" "Eun." "Eunapius"
 "Eunic." "Eunicus" "Euod." "Euodus" "Euph." "Euphorio" "Euphron."
 "Euphronius" "Eup." "Eupolis" "E." "Euripides" "Euryph." "Euryphamus"
 "Eus.Hist." "Eusebius" "Eus." "Eusebius Caesariensis" "Eus.Mynd."
 "Eusebius Myndius" "Eust." "Eustathius" "Eust.Epiph."
 "Eustathius Epiphaniensis" "Eustr." "Eustratius" "Euthycl."
 "Euthycles" "Eutoc." "Eutocius" "Eutolm." "Eutolmius" "Eutych."
 "Eutychianus" "Even." "Evenus" "Ezek." "Ezekiel" "Favorin."
 "Favorinus" "Fest." "Festus" "Firm." "Firmicus Maternus" "Gabriel."
 "Gabrielius" "Gaet." "Gaetulicus, Cn. Lentulus" "Gal." "Galenus"
 "Gell." "Gellius, Aulus" "Gem." "Geminus" "Germ." "Germanicus Caesar"
 "Glauc." "Glaucus Nicopolitanus" "Gorg." "Gorgias" "Greg.Cor."
 "Gregorius Corinthius" "Greg.Cypr." "Gregorius Cyprius" "Hadr.Rh."
 "Hadrianus" "Hadr." "Hadrianus Imperator" "Harmod." "Harmodius"
 "Harp." "Harpocratio" "Harp.Astr."
 "Harpocratio (Medicus et Astrologus)" "Hecat.Abd."
 "Hecataeus Abderita" "Hecat." "Hecataeus Milesius" "Hedyl." "Hedylus"
 "Hegem." "Hegemon" "Hegesand." "Hegesander" "Hegesian." "Hegesianax"
 "Hegesipp.Com." "Hegesippus" "Hegesipp."
 "Hegesippus (Epigrammaticus)" "Hld." "Heliodorus" "Heliod."
 "Heliodorus (Philosophus)" "Heliod.Hist." "Heliodorus (Periegeta)"
 "Hellad." "Helladius" "Hellanic." "Hellanicus" "Henioch." "Heniochus"
 "Heph.Astr." "Hephaestio" "Heph." "Hephaestio (Grammaticus)"
 "Heracl." "Heraclas" "Heraclid.Com." "Heraclides" "Heraclid."
 "Heraclides Tarentinus" "Heraclid.Cum." "Heraclides Cumaeus"
 "Heraclid.Lemb." "Heraclides Lembus" "Heraclid.Pont."
 "Heraclides Ponticus" "Heraclid.Sinop." "Heraclides Sinopensis"
 "Heraclit." "Heraclitus" "Herm." "Hermias Alexandrinus" "Hermesian."
 "Hermesianax" "Herm.Hist." "Hermias" "Herm.Iamb."
 "Hermias (Iambographus)" "Hermipp." "Hermippus" "Hermipp.Hist."
 "Hermippus (Historicus)" "Hermocl." "Hermocles" "Hermocr."
 "Hermocreon" "Hermod." "Hermodorus" "Hermog." "Hermogenes" "Herod."
 "Herodas" "Hdn." "Herodianus" "Herodor." "Herodorus" "Hdt."
 "Herodotus" "Herod.Med." "Herodotus (Medicus)" "Herophil."
 "Herophilus" "Hes." "Hesiodus" "Hsch.Mil." "Hesychius Milesius"
 "Hsch." "Hesychius" "Hices." "Hicesius" "Hierocl."
 "Hierocles Stoicus" "Hierocl.Hist." "Hierocles (Historicus)"
 "Hieronym.Hist." "Hieronymus Cardianus" "Him." "Himerius" "Hipparch."
 "Hipparchus" "Hipparch.Com." "Hipparchus (Comicus)" "Hippias Erythr."
 "Hippias Erythraeus" "Hp." "Hippocrates" "Hippod." "Hippodamus"
 "Hippol." "Hippolytus" "Hippon." "Hipponax" "Hom." "Homerus"
 "Honest." "Honestus" "Horap." "Horapollo" "Hyp." "Hyperides"
 "Hypsicl." "Hypsicles" "Iamb." "Iamblichus" "Ibyc." "Ibycus" "Il."
 "Ilias" "Il.Parv." "Ilias Parva" "Il.Pers." "Iliu Persis" "Iren."
 "Irenaeus" "Is." "Isaeus" "Isid.Trag." "Isidorus" "Isid.Aeg."
 "Isidorus Aegeates" "Isid.Char." "Isidorus Characenus" "Isid."
 "Isidorus Scholasticus" "Isig." "Isigonus" "Isoc." "Isocrates"
 "Isyll." "Isyllus" "Jo.Alex. vel Jo.Gramm." "Joannes Alexandrinus"
 "Jo.Diac." "Joannes Diaconus" "Jo.Gaz." "Joannes Gazaeus" "J."
 "Josephus" "Jul." "Julianus Imperator" "Jul. vel Jul.Aegypt."
 "Julianus Aegyptius" "Jul.Laod." "Julianus Laodicensis" "Junc."
 "Juncus" "Just." "Justinianus" "Juv." "Juvenalis, D. Junius"
 "Lamprocl." "Lamprocles" "Leo Phil." "Leo Philosophus" "Leon."
 "Leonidas Alexandrinus" "Leonid." "Leonidas (Medicus)" "Leont."
 "Leontius" "Lesb.Gramm." "Lesbonax" "Lesb.Rh." "Lesbonax (Rhetor)"
 "Leucipp." "Leucippus" "Lib." "Libanius" "Licymn." "Licymnius"
 "Limen." "Limenius" "Loll." "Lollius Bassus" "Longin." "Longinus"
 "Luc." "Lucianus" "Lucill." "Lucillius" "Lyc." "Lycophron"
 "Lycophronid." "Lycophronides" "Lycurg." "Lycurgus" "Lyd."
 "Lydus, Joannes Laurentius" "Lync." "Lynceus" "Lys." "Lysias"
 "Lysimachid." "Lysimachides" "Lysim." "Lysimachus" "Lysipp."
 "Lysippus" "Macar." "Macarius" "Maced." "Macedonius Thessalonicensis"
 "Macr." "Macrobius" "Maec." "Maecius" "Magn." "Magnes" "Magnus Hist."
 "Magnus" "Maiist." "Maiistas" "Malch." "Malchus" "Mamerc." "Mamercus"
 "Man." "Manetho" "Man.Hist." "Manetho (Historicus)" "Marcellin."
 "Marcellinus" "Marc.Sid." "Marcellus Sidetes" "Marcian." "Marcianus"
 "M.Ant." "Marcus Antoninus" "Marc.Arg." "Marcus Argentarius"
 "Maria Alch." "Maria" "Marian." "Marianus" "Marin." "Marinus"
 "Mar.Vict." "Marius Victorinus" "Mart." "Martialis" "Mart.Cap."
 "Martianus Capella" "Max." "Maximus" "Max.Tyr." "Maximus Tyrius"
 "Megasth." "Megasthenes" "Melamp." "Melampus" "Melanipp."
 "Melanippides" "Melanth.Hist." "Melanthius" "Melanth.Trag."
 "Melanthius (Tragicus)" "Mel." "Meleager" "Meliss." "Melissus"
 "Memn." "Memnon" "Menaechm." "Menaechmus" "Men." "Menander" "Men.Rh."
 "Menander (Rhetor)" "Men.Eph." "Menander Ephesius" "Men.Prot."
 "Menander Protector" "Menecl." "Menecles Barcaeus" "Menecr."
 "Menecrates" "Menecr.Eph." "Menecrates Ephesius" "Menecr.Xanth."
 "Menecrates Xanthius" "Menemach." "Menemachus" "Menesth."
 "Menesthenes" "Menipp." "Menippus" "Menodot." "Menodotus Samius"
 "Mesom." "Mesomedes" "Metag." "Metagenes" "Metrod." "Metrodorus"
 "Metrod.Chius" "Metrodorus Chius" "Metrod.Sceps."
 "Metrodorus Scepsius" "Mich." "Michael Ephesius" "Mimn." "Mimnermus"
 "Mimn.Trag." "Mimnermus (Tragicus)" "Minuc." "Minucianus" "Mithr."
 "Mithradates" "Mnasalc." "Mnasalcas" "Mnesim." "Mnesimachus"
 "Mnesith.Ath." "Mnesitheus Atheniensis" "Mnesith.Cyz."
 "Mnesitheus Cyzicenus" "Moer." "Moeris" "MoschioTrag." "Moschio"
 "Mosch." "Moschus" "Muc.Scaev." "Mucius Scaevola" "Mund."
 "Mundus Munatius" "Musae." "Musaeus" "Music." "Musicius" "Muson."
 "Musonius" "Myrin." "Myrinus" "Myrsil." "Myrsilus" "Myrtil."
 "Myrtilus" "Naumach." "Naumachius" "Nausicr." "Nausicrates"
 "Nausiph." "Nausiphanes" "Neanth." "Neanthes" "Nearch." "Nearchus"
 "Nech." "Nechepso" "Neophr." "Neophron" "Neoptol." "Neoptolemus"
 "Nicaenet." "Nicaenetus" "Nic." "Nicias" "Nicarch." "Nicarchus"
 "Nicoch." "Nicochares" "Nicocl." "Nicocles" "Nicod." "Nicodemus"
 "Nicol.Com." "Nicolaus" "Nicol." "Nicolaus (Rhetor)" "Nic.Dam."
 "Nicolaus Damascenus" "Nicom.Com." "Nicomachus" "Nicom.Trag."
 "Nicomachus (Tragicus)" "Nicom." "Nicomachus Gerasenus"
 "Nicostr.Com." "Nicostratus" "Nicostr." "Nicostratus (Philosophus)"
 "Nonn." "Nonnus" "Noss." "Nossis" "Numen." "Numenius Heracleota"
 "Nymphod." "Nymphodorus" "Ocell." "Ocellus Lucanus" "Od." "Odyssea"
 "Oenom." "Oenomaus" "Olymp.Alch." "Olympiodorus" "Olymp.Hist."
 "Olympiodorus (Historicus)" "Olymp." "Olympiodorus (Philosophus)"
 "Onat." "Onatas" "Onos." "Onosander (Onasander)" "Ophel." "Ophelio"
 "Opp." "Oppianus Apamensis" "Orib." "Oribasius" "Orph." "Orphica"
 "Palaeph." "Palaephatus" "Palch." "Palchus" "Pall." "Palladius"
 "Pamphil." "Pamphilus" "Pancrat." "Pancrates" "Panyas." "Panyasis"
 "Papp." "Pappus" "Parm." "Parmenides" "Parmen." "Parmenio" "Parrhas."
 "Parrhasius" "Parth." "Parthenius" "Patrocl." "Patrocles Thurius"
 "Paul.Aeg." "Paulus Aegineta" "Paul.Al." "Paulus Alexandrinus"
 "Paul.Sil." "Paulus Silentiarius" "Paus." "Pausanias" "Paus.Dam."
 "Pausanias Damascenus" "Paus.Gr." "Pausanias Grammaticus" "Pediasim."
 "Pediasimus" "Pelag.Alch." "Pelagius" "Pempel." "Pempelus" "Perict."
 "Perictione" "Pers." "Persius" "Petos." "Petosiris" "Petron."
 "Petronius" "Petr.Patr." "Petrus Patricius" "Phaedim." "Phaedimus"
 "Phaënn." "Phaënnus" "Phaest." "Phaestus" "Phal." "Phalaecus"
 "Phalar." "Phalaris" "Phan." "Phanias" "Phan.Hist."
 "Phanias (Historicus)" "Phanocl." "Phanocles" "Phanod." "Phanodemus"
 "Pherecr." "Pherecrates" "Pherecyd." "Pherecydes Lerius"
 "Pherecyd.Syr." "Pherecydes Syrius" "Philagr." "Philagrius" "Philem."
 "Philemo" "Philem.Jun." "Philemo Junior" "Philetaer." "Philetaerus"
 "Philippid." "Philippides" "Philipp.Com." "Philippus" "Phil."
 "Philippus (Epigrammaticus)" "Philisc.Com." "Philiscus"
 "Philisc.Trag." "Philiscus (Tragicus)" "Philist." "Philistus"
 "Ph.Epic." "Philo" "Ph." "Philo Judaeus" "Ph.Bybl." "Philo Byblius"
 "Ph.Byz." "Philo Byzantius" "Ph.Tars." "Philo Tarsensis" "Philoch."
 "Philochorus" "Philocl." "Philocles" "Philod.Scarph."
 "Philodamus Scarpheus" "Phld." "Philodemus Gadarensis" "Philol."
 "Philolaus" "Philomnest." "Philomnestus" "Philonid." "Philonides"
 "Phlp." "Philoponus, Joannes" "Philosteph.Com." "Philostephanus"
 "Philosteph.Hist." "Philostephanus (Historicus)" "Philostr."
 "Philostratus" "Philostr.Jun." "Philostratus Junior" "Philox."
 "Philoxenus" "Philox.Gramm." "Philoxenus (Grammaticus)" "Philum."
 "Philumenus" "Philyll." "Philyllius" "Phint." "Phintys" "Phleg."
 "Phlegon Trallianus" "Phoc." "Phocylides" "Phoeb." "Phoebammon"
 "Phoenicid." "Phoenicides" "Phoen." "Phoenix" "Phot." "Photius"
 "Phryn." "Phrynichus" "Phryn.Com." "Phrynichus (Comicus)"
 "Phryn.Trag." "Phrynichus (Tragicus)" "Phylarch." "Phylarchus"
 "Phylotim." "Phylotimus" "Pi." "Pindarus" "Pisand." "Pisander"
 "Pittac." "Pittacus" "Pl.Com." "Plato" "Pl." "Plato (Philosophus)"
 "Pl.Jun." "Plato Junior" "Platon." "Platonius" "Plaut." "Plautus"
 "Plin." "Plinius" "Plot." "Plotinus" "Plu." "Plutarchus"
 "Polem.Hist." "Polemo" "Polem." "Polemo Sophista" "Polioch."
 "Poliochus" "Poll." "Pollux" "Polyaen." "Polyaenus, Julius" "Plb."
 "Polybius" "Plb.Rh." "Polybius Sardianus" "Polycharm." "Polycharmus"
 "Polyclit." "Polyclitus" "Polycr." "Polycrates" "Polystr."
 "Polystratus" "Polyzel." "Polyzelus" "Pomp." "Pompeius" "Pomp.Mac."
 "Pompeius Macer" "Porph." "Porphyrius Tyrius" "Posidipp."
 "Posidippus" "Posidon." "Posidonius" "Pratin." "Pratinas" "Praxag."
 "Praxagoras" "Praxill." "Praxilla" "Priscian." "Priscianus"
 "Prisc.Lyd." "Priscianus Lydus" "Prisc." "Priscus" "Procl." "Proclus"
 "Procop." "Procopius Caesariensis" "Procop.Gaz." "Procopius Gazaeus"
 "Prodic." "Prodicus" "Promathid." "Promathidas" "Protag."
 "Protagoras" "Protagorid." "Protagoridas" "Proxen." "Proxenus"
 "Ps.-Callisth." "Pseudo-Callisthenes" "Ps.-Phoc." "Pseudo-Phocylidea"
 "Ptol." "Ptolemaeus" "Ptol.Ascal." "Ptolemaeus Ascalonita"
 "Ptol.Chenn." "Ptolemaeus Chennos" "Ptol.Euerg."
 "Ptolemaeus Euergetes II" "Ptol.Megalop."
 "Ptolemaeus Megalopolitanus" "Pythaen." "Pythaenetus" "Pythag."
 "Pythagoras" "Pythocl." "Pythocles" "Quint." "Quintilianus" "Q.S."
 "Quintus Smyrnaeus" "Rh." "Rhetores Graeci" "Rhetor." "Rhetorius"
 "Rhian." "Rhianus" "Rhinth." "Rhinthon" "Rufin." "Rufinus" "Ruf."
 "Rufus" "Ruf.Rh." "Rufus (Rhetor)" "Rutil." "Rutilius Lupus"
 "Tull.Sab." "Sabinus, Tullius" "Sacerd." "Sacerdos, Marius Plotius"
 "Sallust." "Sallustius" "Sannyr." "Sannyrio" "Sapph." "Sappho"
 "Satyr." "Satyrus" "Scyl." "Scylax" "Scymn." "Scymnus" "Scythin."
 "Scythinus Teius" "Secund." "Secundus" "Seleuc." "Seleucus"
 "Seleuc.Lyr." "Seleucus (Lyricus)" "Semon." "Semonides" "Seren."
 "Serenus" "Serv." "Servius" "Sever." "Severus" "Sext." "Sextus"
 "S.E." "Sextus Empiricus" "Silen." "Silenus" "Simon." "Simonides"
 "Simp." "Simplicius" "Simyl." "Simylus" "Socr.Arg."
 "Socrates Argivus" "Socr.Cous" "Socrates Cous" "Socr.Rhod."
 "Socrates Rhodius" "Socr." "Socratis et Socraticorum Epistulae"
 "Sol." "Solon" "Sopat." "Sopater" "Sopat.Rh." "Sopater (Rhetor)"
 "Sophil." "Sophilus" "S." "Sophocles" "Sophon" "Sophonias" "Sophr."
 "Sophron" "Sor." "Soranus" "Sosib." "Sosibius" "Sosicr." "Sosicrates"
 "Sosicr.Hist." "Sosicrates (Historicus)" "Sosicr.Rhod."
 "Sosicrates Rhodius" "Sosip." "Sosipater" "Sosiph." "Sosiphanes"
 "Sosith." "Sositheus" "Sostrat." "Sostratus" "Sosyl." "Sosylus"
 "Sotad.Com." "Sotades" "Sotad." "Sotades (Lyricus)" "Speus."
 "Speusippus" "Sphaer.Hist." "Sphaerus" "Staphyl." "Staphylus"
 "Stat.Flacc." "Statyllius Flaccus" "Steph.Com." "Stephanus" "Steph."
 "Stephanus (Philosophus)" "St.Byz." "Stephanus Byzantius" "Stesich."
 "Stesichorus" "Stesimbr." "Stesimbrotus" "Sthenid." "Sthenidas"
 "Stob." "Stobaeus, Joannes" "Str." "Strabo" "Strato Com." "Strato"
 "Strat." "Strato (Epigrammaticus)" "Stratt." "Strattis" "Suet."
 "Suetonius" "Suid." "Suidas" "Sulp.Max." "Sulpicius Maximus" "Sus."
 "Susario" "Sm." "Symmachus" "Syn.Alch." "Synesius" "Syrian."
 "Syrianus" "Telecl." "Teleclides" "Telesill." "Telesilla" "Telest."
 "Telestes" "Ter.Maur." "Terentianus Maurus" "Ter.Scaur."
 "Terentius Scaurus" "Terp." "Terpander" "Thal." "Thales" "Theaet."
 "Theaetetus" "Theagen." "Theagenes" "Theag." "Theages"
 "Themiso Hist." "Themiso" "Them." "Themistius" "Themist."
 "Themistocles" "Theocl." "Theocles" "Theoc." "Theocritus" "Theodect."
 "Theodectes" "Theodorid." "Theodoridas" "Theod." "Theodorus"
 "Theodos." "Theodosius Alexandrinus" "Thd." "Theodotion" "Theognet."
 "Theognetus" "Thgn." "Theognis" "Thgn.Trag." "Theognis (Tragicus)"
 "Thgn.Hist." "Theognis Rhodius" "Theognost." "Theognostus" "Theolyt."
 "Theolytus" "Theon Gymn." "Theon Gymnasiarcha" "Theo Sm."
 "Theon Smyrnaeus" "Theoph." "Theophanes" "Theophil." "Theophilus"
 "Thphr." "Theophrastus" "Theopomp.Com." "Theopompus" "Theopomp.Hist."
 "Theopompus (Historicus)" "Theopomp.Coloph." "Theopompus Colophonius"
 "Thom." "Thomas" "Thom.Mag." "Thomas Magister" "Thrasym."
 "Thrasymachus" "Th." "Thucydides" "Thugen." "Thugenides" "Thyill."
 "Thyillus" "Thymocl." "Thymocles" "Tib." "Tiberius" "Tib.Ill."
 "Tiberius Illustrius" "Tim." "Timotheus (Lyricus)" "Timae."
 "Timaeus (Historicus)" "Ti.Locr." "Timaeus Locrus" "Timag."
 "Timagenes" "Timocl." "Timocles" "Timocr." "Timocreon" "Timostr."
 "Timostratus" "Tim.Com." "Timotheus" "Tim.Gaz." "Timotheus Gazaeus"
 "Titanomach." "Titanomachia" "Trophil." "Trophilus" "Tryph."
 "Tryphiodorus" "Tull.Flacc." "Tullius Flaccus" "Tull.Gem."
 "Tullius Geminus" "Tull.Laur." "Tullius Laurea" "Tymn." "Tymnes"
 "Tyrt." "Tyrtaeus" "Tz." "Tzetzes, Joannes" "Ulp." "Ulpianus" "Uran."
 "Uranius" "Vel.Long." "Velius Longus" "Vett.Val." "Vettius Valens"
 "LXX" "Vetus Testamentum Graece redditum" "Vitr." "Vitruvius"
 "Xanth." "Xanthus" "Xenag." "Xenagoras" "Xenarch." "Xenarchus"
 "Xenocl." "Xenocles" "Xenocr." "Xenocrates" "Xenoph." "Xenophanes"
 "X." "Xenophon" "X.Eph." "Xenophon Ephesius" "Zaleuc." "Zaleucus"
 "Zelot." "Zelotus" "Zeno Eleat." "Zeno Eleaticus" "Zen." "Zenobius"
 "Zenod." "Zenodotus" "Zonae." "Zonaeus" "Zonar." "Zonaras" "Zon."
 "Zonas" "Zopyr.Hist." "Zopyrus" "Zopyr." "Zopyrus (Medicus)"
 "Zos.Alch." "Zosimus" "Zos." "Zosimus (Historicus)"))
  "A hash table containing every author abbreviation in the LSJ.")

(defvar hrm-title-hash
#s(hash-table size 751 test equal rehash-size 1.5 rehash-threshold 0.8125 data
("urn:cts:greekLit:tlg0012.tlg002" "Odyssey"
 "urn:cts:greekLit:tlg0011.tlg001" "Trachiniae"
 "urn:cts:greekLit:tlg0059.tlg005" "Cratylus"
 "urn:cts:greekLit:tlg0012.tlg001" "Iliad"
 "urn:cts:greekLit:tlg0085.tlg005" "Agamemnon"
 "urn:cts:greekLit:tlg0011.tlg006" "Philoctetes"
 "urn:cts:greekLit:tlg0011.tlg004" "Oedipus Tyrannus"
 "urn:cts:greekLit:tlg0006.tlg014" "Helena"
 "urn:cts:greekLit:tlg0019.tlg009" "Frogs"
 "urn:cts:greekLit:tlg0085.tlg003" "Prometheus Vinctus"
 "urn:cts:greekLit:tlg0059.tlg025" "Greater Hippias"
 "urn:cts:greekLit:tlg0006.tlg001" "Cyclops"
 "urn:cts:greekLit:tlg0001.tlg001" "Argonautica"
 "urn:cts:greekLit:tlg0020.tlg002" "Works and Days"
 "urn:cts:greekLit:tlg0023.tlg001" "Halieutica"
 "urn:cts:greekLit:tlg2583.tlg001" "Apotelesmatica"
 "urn:cts:greekLit:tlg0020.tlg001" "Theogony"
 "urn:cts:greekLit:tlg1486.tlg001" "Convivium Atticum"
 "urn:cts:greekLit:tlg0011.tlg008" "Tracking Satyrs"
 "urn:cts:greekLit:tlg0013.tlg002" "Hymn 2 to Demeter"
 "urn:cts:greekLit:tlg0074.tlg005" "Tactica"
 "urn:cts:greekLit:tlg0544.tlg001" "Pyrrhoniae Hypotyposes"
 "urn:cts:greekLit:tlg4013.tlg004" "In Aristotelis Physicorum Libros Commentaria"
 "urn:cts:greekLit:tlg0543.tlg001" "Histories"
 "urn:cts:greekLit:tlg0007.tlg050" "Cato the Younger"
 "urn:cts:greekLit:tlg0542.tlg001" "Onomasticon"
 "urn:cts:greekLit:tlg0008.tlg001" "Deipnosophistae"
 "urn:cts:greekLit:tlg0006.tlg017" "Bacchae"
 "urn:cts:greekLit:tlg0006.tlg016" "Orestes"
 "urn:cts:greekLit:tlg0086.tlg003" "Res Publica Atheniensium"
 "urn:cts:greekLit:tlg0544.tlg002" "Adversus Mathematicos"
 "urn:cts:greekLit:tlg2023.tlg002" "Protrepticus"
 "urn:cts:greekLit:tlg0708.tlg001" "ΠΕΡΙ ΟΜΟΙΩΝ ΚΑΙ ΔΙΑΦΟΡΩΝ ΛΕΞΕΩΝ"
 "urn:cts:greekLit:tlg0033.tlg002" "Pythian"
 "urn:cts:greekLit:tlg0086.tlg005" "De caelo"
 "urn:cts:greekLit:tlg1264.tlg001" "Fragmenta Logica et Physica"
 "urn:cts:greekLit:tlg2000.tlg001" "Enneades"
 "urn:cts:greekLit:tlg0031.tlg008" "Second Epistle to the Corinthians"
 "urn:cts:greekLit:tlg0003.tlg001" "History of the Peloponnesian War"
 "urn:cts:greekLit:tlg0032.tlg001" "Hellenica"
 "urn:cts:greekLit:tlg0553.tlg001" "Onirocriticon"
 "urn:cts:greekLit:tlg0018.tlg001" "De Opificio Mundi"
 "urn:cts:greekLit:tlg0007.tlg058" "Antony"
 "urn:cts:greekLit:tlg0527.tlg049" "Jeremias"
 "urn:cts:greekLit:tlg0033.tlg003" "Nemean"
 "urn:cts:greekLit:tlg0016.tlg001" "The Histories"
 "urn:cts:greekLit:tlg0010.tlg014" "Nicocles or the Cyprians"
 "urn:cts:greekLit:tlg0032.tlg006" "Anabasis"
 "urn:cts:greekLit:tlg0099.tlg001" "Geographiae Chrestomathia"
 "urn:cts:greekLit:tlg0033.tlg001" "Olympian"
 "urn:cts:greekLit:tlg0011.tlg007" "Oedipus at Colonus"
 "urn:cts:greekLit:tlg2034.tlg003" "De abstinentia"
 "urn:cts:greekLit:tlg0059.tlg019" "Laches"
 "urn:cts:greekLit:tlg0059.tlg012" "Phaedrus"
 "urn:cts:greekLit:tlg0062.tlg046" "Lexiphanes"
 "urn:cts:greekLit:tlg0014.tlg017" "On the Treaty with Alexander"
 "urn:cts:latinLit:phi0474.phi057" "Letters to Atticus"
 "urn:cts:greekLit:tlg0233.tlg001" "Fragmentum (128)"
 "urn:cts:greekLit:tlg0627.tlg012" "Aphorismi"
 "urn:cts:greekLit:tlg0086.tlg014" "Historia animalium"
 "urn:cts:greekLit:tlg0074.tlg001" "Anabasis"
 "urn:cts:greekLit:tlg0014.tlg058" "Against Theocrines"
 "urn:cts:greekLit:tlg0007.tlg061" "Brutus"
 "urn:cts:greekLit:tlg0007.tlg011" "Camillus"
 "urn:cts:greekLit:tlg0059.tlg006" "Theaetetus"
 "urn:cts:greekLit:tlg0059.tlg011" "Symposium"
 "urn:cts:greekLit:tlg0014.tlg019" "De Falsa Legatione"
 "urn:cts:greekLit:tlg0059.tlg010" "Philebus"
 "urn:cts:greekLit:tlg0019.tlg003" "Clouds"
 "urn:cts:greekLit:tlg0059.tlg030" "Republic"
 "urn:cts:greekLit:tlg0059.tlg031" "Timaeus"
 "urn:cts:greekLit:tlg0081.tlg006" "De Demosthenis dictione"
 "urn:cts:greekLit:tlg2018.tlg001" "Praeparatio Evangelica"
 "urn:cts:greekLit:tlg0086.tlg021" "De animalium motione"
 "urn:cts:greekLit:tlg0059.tlg034" "Laws"
 "urn:cts:greekLit:tlg1764.tlg001" "Anthologiarum libri"
 "urn:cts:greekLit:tlg0006.tlg005" "Hippolytus"
 "urn:cts:greekLit:tlg0014.tlg021" "Against Meidias"
 "urn:cts:greekLit:tlg0006.tlg010" "Ion"
 "urn:cts:greekLit:tlg0007.tlg060" "Dion"
 "urn:cts:greekLit:tlg0007.tlg007" "Solon"
 "urn:cts:latinLit:phi0474.phi049" "Tusculanae Disputationes"
 "urn:cts:greekLit:tlg0085.tlg004" "Septem Contra Thebes"
 "urn:cts:greekLit:tlg0032.tlg007" "Cyropaedia"
 "urn:cts:greekLit:tlg0011.tlg005" "Electra"
 "urn:cts:greekLit:tlg0032.tlg013" "On the Art of Horsemanship"
 "urn:cts:greekLit:tlg0013.tlg004" "Hymn 4 to Hermes"
 "urn:cts:greekLit:tlg0085.tlg007" "Eumenides"
 "urn:cts:greekLit:tlg0627.tlg006" "Epidemiarum"
 "urn:cts:greekLit:tlg0093.tlg005" "On Fire"
 "urn:cts:greekLit:tlg0093.tlg001" "Historia plantarum"
 "urn:cts:greekLit:tlg0627.tlg050" "De habitu decenti"
 "urn:cts:greekLit:tlg0527.tlg034" "Ecclesiasticus sive Siracides (Sapientia Jesu filii Sirach)"
 "urn:cts:greekLit:tlg0627.tlg004" "De diaeta in morbis acutis"
 "urn:cts:greekLit:tlg0527.tlg027" "Psalmi"
 "urn:cts:greekLit:tlg0007.tlg063" "Aratus"
 "urn:cts:greekLit:tlg0557.tlg002" "The Handbook"
 "urn:cts:greekLit:tlg0071.tlg001" "Anonymi (Arriani, ut fertur) periplus maris Erythraei"
 "urn:cts:greekLit:tlg0614.tlg001" "Fabulae Aesopeae"
 "urn:cts:greekLit:tlg0085.tlg001" "Supplices"
 "urn:cts:greekLit:tlg0527.tlg023" "Machabaeorum i"
 "urn:cts:greekLit:tlg0059.tlg036" "Letters"
 "urn:cts:greekLit:tlg0011.tlg002" "Antigone"
 "urn:cts:greekLit:tlg0006.tlg004" "Heracleidae"
 "urn:cts:greekLit:tlg0527.tlg001" "Genesis"
 "urn:cts:greekLit:tlg0527.tlg002" "Exodus"
 "urn:cts:greekLit:tlg0007.tlg048" "Caesar"
 "urn:cts:greekLit:tlg0062.tlg044" "Toxaris vel amicitia"
 "urn:cts:greekLit:tlg0627.tlg025" "De affectionibus"
 "urn:cts:greekLit:tlg0035.tlg001" "Eros Drapeta"
 "urn:cts:greekLit:tlg0006.tlg008" "The Suppliant Maidens"
 "urn:cts:greekLit:tlg0007.tlg057" "Demetrius"
 "urn:cts:greekLit:tlg0084.tlg001" "Orbis Descriptio"
 "urn:cts:greekLit:tlg0640.tlg001" "Epistulae"
 "urn:cts:greekLit:tlg0085.tlg002" "Persians"
 "urn:cts:greekLit:tlg0006.tlg013" "Iphigenia in Tauris"
 "urn:cts:greekLit:tlg0006.tlg011" "The Trojan Women"
 "urn:cts:greekLit:tlg0006.tlg015" "Phoenissae"
 "urn:cts:greekLit:tlg0033.tlg004" "Isthmean"
 "urn:cts:greekLit:tlg0592.tlg004" "Περὶ ἰδεῶν λόγου"
 "urn:cts:greekLit:tlg0658.tlg001" "Aethiopica"
 "urn:cts:greekLit:tlg0032.tlg004" "Symposium"
 "urn:cts:greekLit:tlg0006.tlg018" "Iphigenia Aulidensis"
 "urn:cts:greekLit:tlg2200.tlg004" "Oratio 1"
 "urn:cts:greekLit:tlg0059.tlg002" "Apology"
 "urn:cts:greekLit:tlg0032.tlg009" "Agesilaus"
 "urn:cts:greekLit:tlg0554.tlg001" "De Chaerea et Callirhoe"
 "urn:cts:greekLit:tlg0059.tlg009" "Parmenides"
 "urn:cts:greekLit:tlg0019.tlg007" "Lysistrata"
 "urn:cts:greekLit:tlg0031.tlg006" "Epistle to the Romans"
 "urn:cts:greekLit:tlg0031.tlg027" "Apocalypse"
 "urn:cts:greekLit:tlg0058.tlg001" "Poliorcetica"
 "urn:cts:greekLit:tlg0082.tlg002" "De adverbiis"
 "urn:cts:greekLit:tlg0671.tlg001" "De venenatis animalibus eorumque remediis"
 "urn:cts:greekLit:tlg0732.tlg004" "In Aristotelis Metaphysica Commentaria"
 "urn:cts:greekLit:tlg4031.tlg002" "In Aristotelis Ethica Nicomachea I Commentaria"
 "urn:cts:greekLit:tlg0031.tlg015" "First Timothy"
 "urn:cts:greekLit:tlg0031.tlg005" "Acts of the Apostles"
 "urn:cts:greekLit:tlg0096.tlg002" "Fabulae"
 "urn:cts:greekLit:tlg0527.tlg004" "Numbers"
 "urn:cts:greekLit:tlg0527.tlg024" "Machabaeorum ii"
 "urn:cts:greekLit:tlg0031.tlg021" "1 Peter"
 "urn:cts:greekLit:tlg0363.tlg007" "Apotelesmatica (= Tetrabiblos)"
 "urn:cts:greekLit:tlg2034.tlg005" "Ad Marcellam"
 "urn:cts:greekLit:tlg0627.tlg003" "Prognosticon"
 "urn:cts:greekLit:tlg0059.tlg023" "Gorgias"
 "urn:cts:greekLit:tlg0032.tlg003" "Οἰκονομικός"
 "urn:cts:greekLit:tlg0540.tlg013" "Against Agoratus: In Pursuance of a Writ"
 "urn:cts:greekLit:tlg0059.tlg022" "Protagoras"
 "urn:cts:greekLit:tlg0032.tlg002" "Memorabilia"
 "urn:cts:greekLit:tlg0007.tlg055" "Cicero"
 "urn:cts:greekLit:tlg0032.tlg014" "On Hunting"
 "urn:cts:greekLit:tlg0093.tlg010" "De Odoribus"
 "urn:cts:greekLit:tlg0019.tlg006" "Birds"
 "urn:cts:greekLit:tlg0010.tlg017" "On the Peace"
 "urn:cts:greekLit:tlg0627.tlg008" "De officina medici"
 "urn:cts:greekLit:tlg0527.tlg011" "Regnorum I (Samuelis I In Textu Masoretico)"
 "urn:cts:greekLit:tlg0527.tlg035" "Psalmi Salomonis"
 "urn:cts:greekLit:tlg0527.tlg013" "Regnorum III (Regum I In Textu Masoretico)"
 "urn:cts:greekLit:tlg0527.tlg014" "Regnorum IV (Regum II In Textu Masoretico)"
 "urn:cts:greekLit:tlg0527.tlg012" "Regnorum II (Samuelis II In Textu Masoretico)"
 "urn:cts:greekLit:tlg0527.tlg056" "Daniel (translatio Graeca)"
 "urn:cts:greekLit:tlg4033.tlg003" "In Ethica Nicomachea Paraphrasis (Pseudepigraphum Olim A Constantino Palaeocappa confectum et olim sub auctore Heliodoro Prusensi vel Andronico Rhodio vel Olympiodoro)"
 "urn:cts:greekLit:tlg0031.tlg010" "Ephesians"
 "urn:cts:greekLit:tlg0627.tlg051" "Praeceptiones"
 "urn:cts:greekLit:tlg0527.tlg032" "Job"
 "urn:cts:greekLit:tlg0031.tlg003" "Gospel according to Luke"
 "urn:cts:greekLit:tlg0527.tlg048" "Isaias"
 "urn:cts:greekLit:tlg0031.tlg004" "Gospel according to John"
 "urn:cts:greekLit:tlg0627.tlg010" "De articulis"
 "urn:cts:greekLit:tlg0006.tlg012" "Electra"
 "urn:cts:greekLit:tlg0540.tlg006" "Against Andocides"
 "urn:cts:greekLit:tlg0010.tlg015" "Evagoras"
 "urn:cts:greekLit:tlg0059.tlg024" "Meno"
 "urn:cts:greekLit:tlg0007.tlg004" "Lycurgus"
 "urn:cts:greekLit:tlg0563.tlg001" "Dialexeis"
 "urn:cts:greekLit:tlg0057.tlg017" "De usu partium corporis humani I-XI"
 "urn:cts:greekLit:tlg0014.tlg018" "On the Crown"
 "urn:cts:greekLit:tlg0007.tlg013" "Fabius Maximus"
 "urn:cts:greekLit:tlg0010.tlg011" "Panegyricus"
 "urn:cts:greekLit:tlg0059.tlg021" "Euthydemus"
 "urn:cts:greekLit:tlg0014.tlg063" "Letters"
 "urn:cts:greekLit:tlg0006.tlg009" "Heracles"
 "urn:cts:greekLit:tlg0059.tlg004" "Phaedo"
 "urn:cts:greekLit:tlg0007.tlg032" "Lysander"
 "urn:cts:greekLit:tlg0627.tlg009" "De fracturis"
 "urn:cts:greekLit:tlg0032.tlg011" "Ways and Means"
 "urn:cts:greekLit:tlg4024.tlg001" "Historiae"
 "urn:cts:greekLit:tlg0627.tlg022" "De liquidorum usu"
 "urn:cts:greekLit:tlg0540.tlg003" "Against Simon: Defense"
 "urn:cts:greekLit:tlg0059.tlg001" "Euthyphro"
 "urn:cts:greekLit:tlg0540.tlg001" "On the Murder of Eratosthenes"
 "urn:cts:greekLit:tlg0010.tlg004" "Concerning the Team of Horses"
 "urn:cts:greekLit:tlg0062.tlg022" "Timon"
 "urn:cts:greekLit:tlg0062.tlg029" "Somnium sive vita Luciani"
 "urn:cts:greekLit:tlg0062.tlg025" "Revivescentes sive piscator"
 "urn:cts:greekLit:tlg0010.tlg019" "Antidosis"
 "urn:cts:greekLit:tlg0014.tlg002" "Olynthiac 2"
 "urn:cts:greekLit:tlg0059.tlg008" "Πολιτικός"
 "urn:cts:greekLit:tlg0014.tlg061" "The Erotic Essay"
 "urn:cts:greekLit:tlg0527.tlg005" "Deuteronomium"
 "urn:cts:greekLit:tlg0062.tlg018" "Juppiter tragoedus"
 "urn:cts:greekLit:tlg0031.tlg001" "Matthew"
 "urn:cts:greekLit:tlg0527.tlg016" "Paralipomenon II sive Chronicon II"
 "urn:cts:greekLit:tlg0007.tlg012" "Pericles"
 "urn:cts:greekLit:tlg0059.tlg020" "Lysis"
 "urn:cts:greekLit:tlg0540.tlg012" "Against Eratosthenes, who had been One of the Thirty: Spoken by Lysias Himself"
 "urn:cts:greekLit:tlg0010.tlg021" "Panathenaicus"
 "urn:cts:greekLit:tlg0010.tlg002" "Against Callimachus"
 "urn:cts:greekLit:tlg0014.tlg055" "Against Callicles"
 "urn:cts:greekLit:tlg0015.tlg001" "Ab excessu divi Marci"
 "urn:cts:greekLit:tlg0540.tlg002" "Funeral Oration for the Men who Supported the Corinthians"
 "urn:cts:greekLit:tlg0014.tlg001" "First Olynthiac"
 "urn:cts:greekLit:tlg0014.tlg006" "Second Philippic"
 "urn:cts:greekLit:tlg0062.tlg035" "Menippus sive necyomantia"
 "urn:cts:greekLit:tlg0527.tlg036" "Osee"
 "urn:cts:greekLit:tlg0527.tlg031" "Canticum"
 "urn:cts:greekLit:tlg0031.tlg007" "First Corinthians"
 "urn:cts:greekLit:tlg0031.tlg022" "2 Peter"
 "urn:cts:greekLit:tlg0059.tlg037" "Definitiones"
 "urn:cts:greekLit:tlg0527.tlg021" "Tobias (Cod. Vaticanus + Cod. Alexandrinus)"
 "urn:cts:greekLit:tlg0031.tlg002" "Gospel of Mark"
 "urn:cts:greekLit:tlg0013.tlg003" "Hymn 3 to Delian and Pythian Apollo"
 "urn:cts:greekLit:tlg0006.tlg007" "Hecuba"
 "urn:cts:greekLit:tlg0007.tlg019" "Aemilius Paulus"
 "urn:cts:greekLit:tlg0527.tlg050" "Baruch"
 "urn:cts:greekLit:tlg0559.tlg001" "Pneumatica"
 "urn:cts:greekLit:tlg0565.tlg001" "Gynaeciorum Libri IV"
 "urn:cts:greekLit:tlg0093.tlg004" "De lapidibus"
 "urn:cts:greekLit:tlg0627.tlg036" "De muliebribus"
 "urn:cts:greekLit:tlg0527.tlg051" "Threni seu Lamentationes"
 "urn:cts:greekLit:tlg0007.tlg002" "Romulus"
 "urn:cts:greekLit:tlg0059.tlg032" "Critias"
 "urn:cts:greekLit:tlg0627.tlg023" "De morbis I"
 "urn:cts:greekLit:tlg0086.tlg030" "De partibus animalium"
 "urn:cts:greekLit:tlg0011.tlg003" "Ajax"
 "urn:cts:greekLit:tlg0062.tlg027" "De Sacrificiis"
 "urn:cts:greekLit:tlg0540.tlg025" "Defense Against a Charge of Subverting the Democracy"
 "urn:cts:greekLit:tlg0085.tlg006" "Libation Bearers"
 "urn:cts:greekLit:tlg0527.tlg006" "Josue (Cod. Vaticanus + Cod. Alexandrinus)"
 "urn:cts:greekLit:tlg0551.tlg017" "Civil Wars"
 "urn:cts:greekLit:tlg0059.tlg018" "Charmides"
 "urn:cts:greekLit:tlg0019.tlg010" "Ecclesiazusae"
 "urn:cts:greekLit:tlg0551.tlg014" "Mithridatic Wars"
 "urn:cts:greekLit:tlg0551.tlg007" "Wars in Spain"
 "urn:cts:greekLit:tlg0014.tlg008" "On the Chersonese"
 "urn:cts:greekLit:tlg0062.tlg038" "Alexander"
 "urn:cts:greekLit:tlg1600.tlg001" "Imagines"
 "urn:cts:greekLit:tlg1487.tlg001" "Περὶ καταρχῶν"
 "urn:cts:greekLit:tlg0007.tlg065" "Galba"
 "urn:cts:latinLit:phi0474.phi048" "de Finibus Bonorum et Malorum"
 "urn:cts:greekLit:tlg0548.tlg001" "Library"
 "urn:cts:greekLit:tlg0020.tlg003" "Sheild of Heracles"
 "urn:cts:greekLit:tlg0062.tlg047" "Eunuchus"
 "urn:cts:greekLit:tlg0540.tlg021" "Defense Against A Charge Of Taking Bribes: Undesignated"
 "urn:cts:greekLit:tlg0525.tlg001" "Description of Greece"
 "urn:cts:greekLit:tlg0010.tlg003" "Against Lochites"
 "urn:cts:greekLit:tlg0014.tlg043" "Against Macartatus"
 "urn:cts:greekLit:tlg0062.tlg051" "Tyrannicida"
 "urn:cts:greekLit:tlg0086.tlg034" "Ars Poetica"
 "urn:cts:greekLit:tlg0612.tlg001" "Orationes"
 "urn:cts:greekLit:tlg1220.tlg001" "Batrachomyomachia"
 "urn:cts:greekLit:tlg0638.tlg007" "De Gymnastica"
 "urn:cts:greekLit:tlg0527.tlg025" "Machabaeorum iii"
 "urn:cts:greekLit:tlg0086.tlg002" "De anima"
 "urn:cts:greekLit:tlg0086.tlg001" "Analytica priora"
 "urn:cts:greekLit:tlg4020.tlg002" "Eliae (Olim Davidis) In Aristotelis Categorias Commentarium"
 "urn:cts:greekLit:tlg0032.tlg010" "Constitution of the Lacedaimonians"
 "urn:cts:greekLit:tlg0007.tlg041" "Eumenes"
 "urn:cts:greekLit:tlg0551.tlg013" "Syrian Wars"
 "urn:cts:greekLit:tlg0013.tlg001" "Hymn 1 to Dionysus"
 "urn:cts:greekLit:tlg0527.tlg037" "Amos"
 "urn:cts:greekLit:tlg0031.tlg013" "1 Thessalonians"
 "urn:cts:greekLit:tlg0527.tlg003" "Leviticus"
 "urn:cts:greekLit:tlg0527.tlg026" "Machabaeorum iv"
 "urn:cts:greekLit:tlg0627.tlg055" "Epistulae, Decretum, Orationes"
 "urn:cts:greekLit:tlg0074.tlg002" "Indica"
 "urn:cts:greekLit:tlg0062.tlg041" "De Syria dea"
 "urn:cts:greekLit:tlg0010.tlg009" "Helen"
 "urn:cts:greekLit:tlg0059.tlg003" "Crito"
 "urn:cts:greekLit:tlg0010.tlg010" "Busiris"
 "urn:cts:greekLit:tlg0526.tlg003" "De Iudaeorum Vetustate sive Contra Apionem"
 "urn:cts:greekLit:tlg0006.tlg006" "Andromache"
 "urn:cts:greekLit:tlg0059.tlg007" "Sophist"
 "urn:cts:greekLit:tlg0007.tlg039" "Crassus"
 "urn:cts:greekLit:tlg0559.tlg012" "Belopoeica"
 "urn:cts:greekLit:tlg0007.tlg027" "Philopoemen"
 "urn:cts:greekLit:tlg0007.tlg005" "Numa"
 "urn:cts:greekLit:tlg0007.tlg031" "Caius Marius"
 "urn:cts:greekLit:tlg0007.tlg045" "Pompey"
 "urn:cts:greekLit:tlg0014.tlg050" "Apollodorus Against Polycles"
 "urn:cts:greekLit:tlg0014.tlg056" "Against Dionysodorus"
 "urn:cts:greekLit:tlg0062.tlg016" "Cataplus"
 "urn:cts:greekLit:tlg0627.tlg041" "De dentitione"
 "urn:cts:greekLit:tlg0014.tlg054" "Against Conon"
 "urn:cts:greekLit:tlg0032.tlg008" "Hiero"
 "urn:cts:greekLit:tlg2178.tlg001" "Ars rhetorica"
 "urn:cts:greekLit:tlg0627.tlg016" "Prorrheticon I"
 "urn:cts:greekLit:tlg0627.tlg027" "De morbo sacro"
 "urn:cts:greekLit:tlg0014.tlg022" "Against Androtion"
 "urn:cts:greekLit:tlg0010.tlg018" "Areopagiticus"
 "urn:cts:greekLit:tlg0014.tlg032" "Against Zenothemis"
 "urn:cts:greekLit:tlg0014.tlg010" "Philippic 4"
 "urn:cts:greekLit:tlg0028.tlg005" "On the murder of Herodes"
 "urn:cts:greekLit:tlg0014.tlg009" "Third Philippic"
 "urn:cts:greekLit:tlg0086.tlg044" "Topica"
 "urn:cts:greekLit:tlg0014.tlg059" "Theomnestus and Apollodorus Against Neaera"
 "urn:cts:greekLit:tlg0627.tlg032" "De affectionibus interioribus"
 "urn:cts:greekLit:tlg0007.tlg015" "Alcibiades"
 "urn:cts:greekLit:tlg0627.tlg031" "De diaeta"
 "urn:cts:greekLit:tlg0627.tlg001" "De prisca medicina"
 "urn:cts:greekLit:tlg0059.tlg028" "Menexenus"
 "urn:cts:greekLit:tlg0086.tlg015" "De animalium incessu"
 "urn:cts:greekLit:tlg0086.tlg026" "Meteorologica"
 "urn:cts:greekLit:tlg0014.tlg044" "Against Leochares"
 "urn:cts:greekLit:tlg0062.tlg021" "Icaromenippus"
 "urn:cts:greekLit:tlg0014.tlg057" "Against Eubulides"
 "urn:cts:greekLit:tlg0014.tlg004" "Philippic 1"
 "urn:cts:greekLit:tlg0062.tlg028" "Adversus indoctum et libros multos ementem"
 "urn:cts:greekLit:tlg0527.tlg018" "Esdras ii (Ezra et Nehemias in textu Masoretico)"
 "urn:cts:greekLit:tlg0086.tlg031" "Physica"
 "urn:cts:greekLit:tlg0014.tlg035" "Against Lacritus"
 "urn:cts:greekLit:tlg0093.tlg009" "Characters"
 "urn:cts:greekLit:tlg0007.tlg052" "Tiberius and Caius Gracchus"
 "urn:cts:greekLit:tlg0551.tlg009" "Punic Wars"
 "urn:cts:greekLit:tlg0540.tlg022" "Against The Corn-Dealers"
 "urn:cts:greekLit:tlg0014.tlg034" "Against Phormio"
 "urn:cts:greekLit:tlg0540.tlg009" "For The Soldier"
 "urn:cts:greekLit:tlg0006.tlg019" "Rhesus"
 "urn:cts:greekLit:tlg0086.tlg017" "De interpretatione"
 "urn:cts:greekLit:tlg0007.tlg016" "Caius Marcius Coriolanus"
 "urn:cts:greekLit:tlg0007.tlg054" "Demosthenes"
 "urn:cts:greekLit:tlg4015.tlg009" "In Aristotelis Physicorum Libros Commentaria"
 "urn:cts:greekLit:tlg0032.tlg012" "On the Cavalry Commander"
 "urn:cts:greekLit:tlg0014.tlg026" "Against Aristogeiton II"
 "urn:cts:greekLit:tlg0007.tlg030" "Pyrrhus"
 "urn:cts:greekLit:tlg0062.tlg011" "Macrobii"
 "urn:cts:greekLit:tlg0561.tlg001" "Daphnis and Chloe"
 "urn:cts:greekLit:tlg0007.tlg033" "Sulla"
 "urn:cts:greekLit:tlg0010.tlg020" "To Philip"
 "urn:cts:greekLit:tlg0012.tlg003" "Homer’s Epigrams"
 "urn:cts:greekLit:tlg0007.tlg026" "Comparison of Aristides and Marcus Cato"
 "urn:cts:greekLit:tlg0083.tlg003" "De Bospori Navigatione"
 "urn:cts:greekLit:tlg0086.tlg045" "On Virtues and Vices"
 "urn:cts:greekLit:tlg0527.tlg010" "Ruth"
 "urn:cts:greekLit:tlg0615.tlg001" "In Ethica Nichomachea Commentaria"
 "urn:cts:greekLit:tlg0062.tlg034" "Anacharsis"
 "urn:cts:greekLit:tlg0062.tlg015" "Convivium"
 "urn:cts:greekLit:tlg0014.tlg047" "Against Evergus and Mnesibulus"
 "urn:cts:greekLit:tlg0627.tlg037" "De virginum morbis"
 "urn:cts:greekLit:tlg0014.tlg013" "On Organization"
 "urn:cts:greekLit:tlg0627.tlg019" "De natura hominis"
 "urn:cts:greekLit:tlg0007.tlg044" "Agesilaus"
 "urn:cts:greekLit:tlg2032.tlg001" "Synagoge"
 "urn:cts:greekLit:tlg0552.tlg001" "De sphaera et cylindro"
 "urn:cts:greekLit:tlg0010.tlg006" "Aegineticus"
 "urn:cts:greekLit:tlg1210.tlg001" "De Sphaera Quae Movetur"
 "urn:cts:greekLit:tlg0014.tlg024" "Against Timocrates"
 "urn:cts:greekLit:tlg0088.tlg001" "Harmonics"
 "urn:cts:greekLit:tlg0014.tlg023" "Against Aristocrates"
 "urn:cts:greekLit:tlg0540.tlg007" "Before the Areopagus: Defense in the Matter of the Olive-Stump"
 "urn:cts:greekLit:tlg0031.tlg012" "Colossians"
 "urn:cts:greekLit:tlg0014.tlg060" "The Funeral Speech"
 "urn:cts:greekLit:tlg0086.tlg043" "De spiritu"
 "urn:cts:greekLit:tlg0059.tlg026" "Hippias Minor"
 "urn:cts:greekLit:tlg0059.tlg027" "Ion"
 "urn:cts:greekLit:tlg0540.tlg020" "For Polystratus"
 "urn:cts:greekLit:tlg0007.tlg049" "Phocion"
 "urn:cts:greekLit:tlg0007.tlg042" "Sertorius"
 "urn:cts:greekLit:tlg0062.tlg039" "Imagines"
 "urn:cts:greekLit:tlg0010.tlg013" "To Nicocles"
 "urn:cts:greekLit:tlg0007.tlg010" "Themistocles"
 "urn:cts:greekLit:tlg0732.tlg006" "In Aristotelis Topicorum Libros Octo Commentaria"
 "urn:cts:greekLit:tlg2586.tlg001" "Διαίρεσις τῶν ἐπιδεικτικῶν"
 "urn:cts:greekLit:tlg1486.tlg002" "Fragmenta"
 "urn:cts:greekLit:tlg0010.tlg012" "Plataicus"
 "urn:cts:greekLit:tlg0007.tlg018" "Timoleon"
 "urn:cts:greekLit:tlg0014.tlg016" "For the People of Megalopolis"
 "urn:cts:greekLit:tlg0540.tlg024" "On The Refusal Of A Pension to the Invalid"
 "urn:cts:greekLit:tlg0540.tlg016" "In Defense of Mantitheus"
 "urn:cts:greekLit:tlg0014.tlg005" "On the Peace"
 "urn:cts:greekLit:tlg0082.tlg001" "De pronominibus"
 "urn:cts:greekLit:tlg0062.tlg031" "Philopseudes sive incredulus"
 "urn:cts:greekLit:tlg0007.tlg035" "Cimon"
 "urn:cts:greekLit:tlg0093.tlg006" "Metaphysics"
 "urn:cts:greekLit:tlg0527.tlg020" "Judith"
 "urn:cts:greekLit:tlg0062.tlg033" "De mercede conductis potentium familiaribus"
 "urn:cts:latinLit:phi0474.phi056" "Letters to his Friends"
 "urn:cts:greekLit:tlg2050.tlg001" "Vitae Sophistarum"
 "urn:cts:greekLit:tlg0010.tlg016" "Archidamus"
 "urn:cts:greekLit:tlg0082.tlg004" "De constructione"
 "urn:cts:greekLit:tlg0551.tlg004" "Samnite History"
 "urn:cts:greekLit:tlg0007.tlg025" "Marcus Cato"
 "urn:cts:greekLit:tlg0627.tlg017" "Coa praesagia"
 "urn:cts:greekLit:tlg0086.tlg042" "De somno et vigilia"
 "urn:cts:greekLit:tlg4013.tlg003" "In Aristotelis Categorias Commentarium"
 "urn:cts:greekLit:tlg0066.tlg001" "Descriptio Graeciae"
 "urn:cts:greekLit:tlg1181.tlg001" "De magnitudinibus et distantiis solis et lunae"
 "urn:cts:greekLit:tlg0627.tlg046" "De alimento"
 "urn:cts:greekLit:tlg0014.tlg020" "Against Leptines"
 "urn:cts:greekLit:tlg0014.tlg037" "Against Pantaenetus"
 "urn:cts:greekLit:tlg0014.tlg014" "On the Navy-Boards"
 "urn:cts:greekLit:tlg0540.tlg004" "On A Wound By Premeditation: Client and Opponent Unknown"
 "urn:cts:greekLit:tlg0010.tlg007" "To Demonicus"
 "urn:cts:greekLit:tlg0358.tlg001" "Introductio arithmetica"
 "urn:cts:greekLit:tlg0013.tlg005" "Hymn 5 to Aphrodite"
 "urn:cts:greekLit:tlg0540.tlg014" "Against Alcibiades: For Deserting the Ranks"
 "urn:cts:greekLit:tlg0540.tlg015" "Against Alcibiades: For Refusal of Military Service"
 "urn:cts:greekLit:tlg0014.tlg025" "Against Aristogeiton I"
 "urn:cts:greekLit:tlg0010.tlg008" "Against the Sophists"
 "urn:cts:greekLit:tlg0007.tlg021" "Pelopidas"
 "urn:cts:greekLit:tlg0007.tlg036" "Lucullus"
 "urn:cts:greekLit:tlg0627.tlg014" "Lex"
 "urn:cts:greekLit:tlg0007.tlg051" "Agis and Cleomenes"
 "urn:cts:greekLit:tlg0007.tlg001" "Theseus"
 "urn:cts:greekLit:tlg0068.tlg001" "Ad Nicomedem regem, vv. 1-980"
 "urn:cts:greekLit:tlg0733.tlg001" "Quaestiones medicae et problemata physica"
 "urn:cts:greekLit:tlg0627.tlg035" "De octimestri partu"
 "urn:cts:greekLit:tlg0627.tlg018" "De arte"
 "urn:cts:greekLit:tlg0627.tlg033" "De natura muliebri"
 "urn:cts:greekLit:tlg0013.tlg006" "Hymn 6 to Aphrodite"
 "urn:cts:greekLit:tlg0013.tlg032" "Hymn 32 To Selene"
 "urn:cts:greekLit:tlg0013.tlg017" "Hymn 17 To the Dioscuri"
 "urn:cts:greekLit:tlg0013.tlg012" "Hymn 12 to Hera"
 "urn:cts:greekLit:tlg0013.tlg027" "Hymn 27 to Artemis"
 "urn:cts:greekLit:tlg0540.tlg026" "On the Scrutiny of Evandros"
 "urn:cts:greekLit:tlg0693.tlg002" "Introductio in Platonem"
 "urn:cts:greekLit:tlg1272.tlg001" "Caelestia"
 "urn:cts:greekLit:tlg0082.tlg003" "De Conjuctionibus"
 "urn:cts:greekLit:tlg0627.tlg007" "De capitis vulneribus"
 "urn:cts:greekLit:tlg4019.tlg003" "In Aristotelis Meteora Commentaria"
 "urn:cts:greekLit:tlg0527.tlg019" "Esther"
 "urn:cts:greekLit:tlg0059.tlg035" "Epinomis"
 "urn:cts:greekLit:tlg0086.tlg013" "De generatione et corruptione"
 "urn:cts:greekLit:tlg0565.tlg003" "De Fasciis"
 "urn:cts:greekLit:tlg0007.tlg006" "Comparison of Lycurgus and Numa"
 "urn:cts:greekLit:tlg0093.tlg003" "De sensu et sensibilibus"
 "urn:cts:greekLit:tlg0559.tlg002" "De automatis"
 "urn:cts:greekLit:tlg0540.tlg033" "Olympic Oration"
 "urn:cts:greekLit:tlg0007.tlg038" "Nicias"
 "urn:cts:greekLit:tlg0062.tlg067" "Dialogi Marini"
 "urn:cts:greekLit:tlg0627.tlg015" "De humoribus"
 "urn:cts:latinLit:phi0474.phi050" "de Natura Deorum"
 "urn:cts:greekLit:tlg0031.tlg009" "Epistle to the Galatians"
 "urn:cts:greekLit:tlg0062.tlg049" "Pseudologista"
 "urn:cts:greekLit:tlg0592.tlg001" "Progymnasmata [Dub.]"
 "urn:cts:greekLit:tlg0540.tlg019" "On the Property of Aristophanes: Against the Treasury"
 "urn:cts:greekLit:tlg0540.tlg032" "Against Diogeiton"
 "urn:cts:greekLit:tlg0014.tlg027" "Against Aphobus I"
 "urn:cts:greekLit:tlg0013.tlg019" "Hymn 19 to Pan"
 "urn:cts:greekLit:tlg2200.tlg005" "Declamatio 1"
 "urn:cts:greekLit:tlg0014.tlg003" "Olynthiac 3"
 "urn:cts:greekLit:tlg0014.tlg062" "Exordia"
 "urn:cts:greekLit:tlg0527.tlg042" "Nahum"
 "urn:cts:greekLit:tlg0527.tlg029" "Proverbia"
 "urn:cts:greekLit:tlg0062.tlg045" "De saltatione"
 "urn:cts:greekLit:tlg0013.tlg031" "Hymn 31 to Helios"
 "urn:cts:greekLit:tlg0062.tlg048" "De astrologia"
 "urn:cts:greekLit:tlg4015.tlg007" "In Libros De Generatione Animalium Commentaria"
 "urn:cts:greekLit:tlg0014.tlg038" "Against Nausimachus and Xenopeithes"
 "urn:cts:greekLit:tlg0062.tlg007" "Nigrinus"
 "urn:cts:greekLit:tlg1286.tlg001" "Poimandres"
 "urn:cts:greekLit:tlg0067.tlg001" "De Rubro Mari"
 "urn:cts:greekLit:tlg2034.tlg002" "Vita Pythagorae"
 "urn:cts:greekLit:tlg0527.tlg052" "Epistula Jeremiae"
 "urn:cts:greekLit:tlg0007.tlg024" "Aristides"
 "urn:cts:greekLit:tlg0627.tlg024" "De genitura"
 "urn:cts:greekLit:tlg0527.tlg053" "Ezechiel"
 "urn:cts:greekLit:tlg0527.tlg015" "Paralipomenon I sive Chronicon I"
 "urn:cts:greekLit:tlg0014.tlg036" "For Phormio"
 "urn:cts:greekLit:tlg0059.tlg017" "Theages"
 "urn:cts:greekLit:tlg0014.tlg048" "Against Olympiodorus"
 "urn:cts:greekLit:tlg0555.tlg001" "Protrepticus"
 "urn:cts:greekLit:tlg0007.tlg022" "Marcellus"
 "urn:cts:greekLit:tlg0014.tlg040" "Against Boeotus II"
 "urn:cts:greekLit:tlg0607.tlg001" "Προγυμνάσματα"
 "urn:cts:greekLit:tlg0031.tlg023" "First Letter of John"
 "urn:cts:greekLit:tlg0014.tlg051" "On the Trierarchic Crown"
 "urn:cts:greekLit:tlg0031.tlg011" "Letter to the Philippians"
 "urn:cts:greekLit:tlg0062.tlg017" "Juppiter confutatus"
 "urn:cts:greekLit:tlg0527.tlg046" "Zacharias"
 "urn:cts:greekLit:tlg0062.tlg020" "Prometheus"
 "urn:cts:greekLit:tlg0057.tlg001" "Adhortatio ad artes addiscendas"
 "urn:cts:greekLit:tlg0031.tlg017" "Letter to Titus"
 "urn:cts:greekLit:tlg0014.tlg011" "Answer to Philip’s Letter"
 "urn:cts:greekLit:tlg0010.tlg001" "Against Euthynus"
 "urn:cts:greekLit:tlg0627.tlg029" "De haemorrhoidibus"
 "urn:cts:greekLit:tlg0062.tlg043" "Fugitivi"
 "urn:cts:greekLit:tlg0627.tlg026" "De locis in homine"
 "urn:cts:greekLit:tlg0627.tlg021" "De flatibus"
 "urn:cts:greekLit:tlg0062.tlg037" "Rhetorum praeceptor"
 "urn:cts:greekLit:tlg0627.tlg043" "De carnibus"
 "urn:cts:greekLit:tlg0592.tlg003" "Περὶ εὑρέσεως [Sp.]"
 "urn:cts:greekLit:tlg0627.tlg042" "De glandulis"
 "urn:cts:greekLit:tlg0014.tlg031" "Against Onetor II"
 "urn:cts:greekLit:tlg0559.tlg007" "Dioptra"
 "urn:cts:greekLit:tlg2135.tlg001" "Isagoge musica"
 "urn:cts:greekLit:tlg0010.tlg023" "To the Children of Jason"
 "urn:cts:greekLit:tlg0010.tlg022" "To Dionysius"
 "urn:cts:greekLit:tlg0551.tlg012" "Illyrian Wars"
 "urn:cts:greekLit:tlg0086.tlg006" "Categoriae"
 "urn:cts:greekLit:tlg0057.tlg010" "De naturalibus facultatibus"
 "urn:cts:greekLit:tlg0007.tlg047" "Alexander"
 "urn:cts:greekLit:tlg0062.tlg019" "Gallus"
 "urn:cts:greekLit:tlg1799.tlg001" "Elements"
 "urn:cts:greekLit:tlg0358.tlg002" "Harmonicum enchiridion"
 "urn:cts:greekLit:tlg0540.tlg017" "On The Property Of Eraton"
 "urn:cts:greekLit:tlg0086.tlg037" "De respiratione"
 "urn:cts:greekLit:tlg0014.tlg053" "Apollodorus Against Nicostratus"
 "urn:cts:greekLit:tlg0007.tlg008" "Publicola"
 "urn:cts:greekLit:tlg0013.tlg033" "Hymn 33 To the Dioscuri"
 "urn:cts:greekLit:tlg2034.tlg006" "Isagoge Sive Quinque Voces"
 "urn:cts:greekLit:tlg0592.tlg005" "Περὶ μεθόδου δεινότητος [Sp.]"
 "urn:cts:greekLit:tlg0540.tlg018" "On the Confiscation of the Property Of The Brother Of Nicias"
 "urn:cts:greekLit:tlg0627.tlg049" "De medico"
 "urn:cts:greekLit:tlg0032.tlg005" "Apology"
 "urn:cts:greekLit:tlg0676.tlg001" "Remedy against Incipient Cataracts"
 "urn:cts:greekLit:tlg2034.tlg007" "In Aristotelis Categorias Expositio Per Interrogationem Et Responsionem"
 "urn:cts:greekLit:tlg0014.tlg052" "Apollodorus Against Callippus"
 "urn:cts:greekLit:tlg0551.tlg011" "Macedonian Affairs"
 "urn:cts:greekLit:tlg0551.tlg008" "Hannibalic War"
 "urn:cts:greekLit:tlg0732.tlg010" "De anima"
 "urn:cts:greekLit:tlg0627.tlg020" "De salubri diaeta"
 "urn:cts:greekLit:tlg0627.tlg030" "De fistulis"
 "urn:cts:greekLit:tlg0610.tlg001" "Odysseus"
 "urn:cts:greekLit:tlg0062.tlg009" "De Domo"
 "urn:cts:greekLit:tlg0609.tlg001" "De tropis"
 "urn:cts:greekLit:tlg0540.tlg010" "Against Theomnestus 1"
 "urn:cts:greekLit:tlg0010.tlg005" "Trapeziticus"
 "urn:cts:greekLit:tlg0086.tlg022" "Magna Moralia"
 "urn:cts:latinLit:phi0474.phi040" "Orator"
 "urn:cts:greekLit:tlg4017.tlg001" "In Aristotelis Metaphysica Commentaria"
 "urn:cts:greekLit:tlg0064.tlg001" "Periplus Hannonis"
 "urn:cts:greekLit:tlg0086.tlg041" "De sensu et sensibilibus"
 "urn:cts:greekLit:tlg0540.tlg028" "Against Ergocles: Supplementary"
 "urn:cts:greekLit:tlg0540.tlg031" "Against Philon, On his Scrutiny"
 "urn:cts:greekLit:tlg0627.tlg045" "De corde"
 "urn:cts:greekLit:tlg0527.tlg038" "Michaeas"
 "urn:cts:greekLit:tlg1724.tlg001" "De utilitate mathematicae"
 "urn:cts:greekLit:tlg0014.tlg042" "Against Phaenippus"
 "urn:cts:greekLit:tlg0014.tlg046" "Against Stephanus II"
 "urn:cts:greekLit:tlg0555.tlg002" "Paedagogus"
 "urn:cts:greekLit:tlg0014.tlg030" "Against Onetor I"
 "urn:cts:greekLit:tlg2018.tlg005" "Demonstratio Evangelica"
 "urn:cts:greekLit:tlg2001.tlg039" "In Aristotelis Physica Paraphrasis"
 "urn:cts:greekLit:tlg0062.tlg023" "Charon sive contemplantes"
 "urn:cts:greekLit:tlg4013.tlg001" "In Aristotelis Quattuor Libros De Caelo Commentaria"
 "urn:cts:greekLit:tlg0062.tlg008" "Demonax"
 "urn:cts:greekLit:tlg2137.tlg001" "Harmonica introductio"
 "urn:cts:greekLit:tlg0062.tlg013" "Calumniae non temere credendum"
 "urn:cts:greekLit:tlg2136.tlg001" "Isagoge artis musicae"
 "urn:cts:greekLit:tlg0062.tlg052" "Abdicatus"
 "urn:cts:greekLit:tlg4015.tlg001" "In Aristotelis Categorias Commentarium"
 "urn:cts:greekLit:tlg0031.tlg019" "To the Hebrews"
 "urn:cts:greekLit:tlg0062.tlg030" "De parasito sive artem esse parasiticam"
 "urn:cts:greekLit:tlg0010.tlg026" "To Timotheus"
 "urn:cts:greekLit:tlg0014.tlg007" "On Halonnesus"
 "urn:cts:greekLit:tlg0026.tlg004" "Epistolae"
 "urn:cts:greekLit:tlg0013.tlg007" "Hymn 7 to Dionysus"
 "urn:cts:greekLit:tlg4019.tlg002" "In Categorias Commentarium"
 "urn:cts:latinLit:phi0474.phi058" "Letters to his brother Quintus"
 "urn:cts:greekLit:tlg0007.tlg059" "Comparison of Demetrius and Antony"
 "urn:cts:greekLit:tlg0014.tlg012" "Philip’s Letter"
 "urn:cts:greekLit:tlg0014.tlg039" "Against Boeotus I"
 "urn:cts:greekLit:tlg0062.tlg002" "Hippias"
 "urn:cts:greekLit:tlg0014.tlg049" "Apollodorus Against Timotheus"
 "urn:cts:greekLit:tlg0540.tlg027" "Against Epicrates and his Fellow-envoys: Supplementary"
 "urn:cts:greekLit:tlg0551.tlg005" "Gallic History"
 "urn:cts:greekLit:tlg0059.tlg015" "Hipparchus"
 "urn:cts:greekLit:tlg0014.tlg033" "Against Apaturius"
 "urn:cts:greekLit:tlg0014.tlg045" "Against Stephanus I"
 "urn:cts:greekLit:tlg0014.tlg028" "Against Aphobus II"
 "urn:cts:greekLit:tlg0540.tlg030" "Against Nicomachus"
 "urn:cts:greekLit:tlg4015.tlg005" "In Aristotelis Meteorologicorum Librum Primum Commentarium"
 "urn:cts:greekLit:tlg0007.tlg064" "Artaxerxes"
 "urn:cts:greekLit:tlg0031.tlg016" "Second Epistle to Timothy"
 "urn:cts:greekLit:tlg0592.tlg002" "Περὶ στάσεων"
 "urn:cts:greekLit:tlg0007.tlg028" "Titus Flamininus"
 "urn:cts:greekLit:tlg0627.tlg048" "De natura ossium"
 "urn:cts:greekLit:tlg0627.tlg038" "De superfoetatione"
 "urn:cts:greekLit:tlg0527.tlg039" "Joel"
 "urn:cts:greekLit:tlg0062.tlg036" "De luctu"
 "urn:cts:greekLit:tlg0086.tlg024" "De memoria et reminiscentia"
 "urn:cts:greekLit:tlg0007.tlg017" "Comparison of Alcibiades and Coriolanus"
 "urn:cts:greekLit:tlg4016.tlg004" "In Aristotelis Analyticorum Priorum Librum I Commentarium"
 "urn:cts:greekLit:tlg0062.tlg024" "Vitarum auctio"
 "urn:cts:greekLit:tlg0031.tlg018" "Epistle of Paul to Philemon"
 "urn:cts:greekLit:tlg0732.tlg008" "In Aristotelis Meteorologicorum Libros Commentaria"
 "urn:cts:greekLit:tlg4034.tlg002" "In Parva Naturalia Commentaria"
 "urn:cts:greekLit:tlg0527.tlg017" "Esdras i (liber apocryphus)"
 "urn:cts:greekLit:tlg0086.tlg016" "De insomniis"
 "urn:cts:greekLit:tlg0732.tlg013" "Ἠθικὰ προβλήματα [Sp.]"
 "urn:cts:greekLit:tlg0732.tlg014" "De fato"
 "urn:cts:greekLit:tlg0627.tlg052" "De crisibus"
 "urn:cts:greekLit:tlg4021.tlg002" "In Porphyrii Isagogen Commentarium"
 "urn:cts:greekLit:tlg0057.tlg004" "De sectis ad eos qui introducuntur"
 "urn:cts:greekLit:tlg0627.tlg028" "De ulceribus"
 "urn:cts:greekLit:tlg0007.tlg066" "Otho"
 "urn:cts:greekLit:tlg0062.tlg042" "De morte Peregrini"
 "urn:cts:greekLit:tlg4003.tlg001" "Periplus maris exteri"
 "urn:cts:greekLit:tlg0527.tlg045" "Aggaeus"
 "urn:cts:greekLit:tlg0074.tlg003" "Cynegeticus"
 "urn:cts:greekLit:tlg0014.tlg041" "Against Spudias"
 "urn:cts:greekLit:tlg0007.tlg003" "Comparison of Theseus and Romulus"
 "urn:cts:greekLit:tlg0657.tlg001" "Fragmenta"
 "urn:cts:greekLit:tlg0062.tlg014" "Lis consonantium"
 "urn:cts:greekLit:tlg0014.tlg029" "Against Aphobus III"
 "urn:cts:greekLit:tlg0644.tlg001" "Historiae Animalium Epitome"
 "urn:cts:greekLit:tlg4016.tlg003" "In Aristotelis Librum De Interpretatione Commentarius"
 "urn:cts:greekLit:tlg0527.tlg054" "Susanna (translatio Graeca)"
 "urn:cts:greekLit:tlg0031.tlg014" "Second Letter to the Thessalonians"
 "urn:cts:greekLit:tlg0007.tlg056" "Comparison of Demosthenes and Cicero"
 "urn:cts:greekLit:tlg0057.tlg029" "De animi cuiuslibet peccatorum dignotione et curatione"
 "urn:cts:greekLit:tlg1799.tlg009" "Optica"
 "urn:cts:greekLit:tlg0527.tlg047" "Malachias"
 "urn:cts:greekLit:tlg0059.tlg033" "Minos"
 "urn:cts:greekLit:tlg0007.tlg040" "Comparison of Nicias and Crassus"
 "urn:cts:greekLit:tlg4021.tlg001" "Prolegomena philosophiae"
 "urn:cts:greekLit:tlg1487.tlg002" "Περὶ καταρχῶν (epitome)"
 "urn:cts:greekLit:tlg0062.tlg040" "Pro imaginibus"
 "urn:cts:greekLit:tlg0062.tlg003" "Bacchus"
 "urn:cts:greekLit:tlg2200.tlg008" "Characteres Epistolici [Sp.]"
 "urn:cts:greekLit:tlg0540.tlg023" "Against Pancleon"
 "urn:cts:greekLit:tlg0540.tlg008" "Accusation of Calumny Against Fellow-Members of a Society"
 "urn:cts:greekLit:tlg2178.tlg004" "Fragmenta"
 "urn:cts:greekLit:tlg0552.tlg005" "De planorum aequilibriis"
 "urn:cts:greekLit:tlg0732.tlg007" "In Librum De Sensu Commentarium"
 "urn:cts:greekLit:tlg9019.tlg001" "In Aristotelis Librum De Interpretatione Commentarium"
 "urn:cts:greekLit:tlg0065.tlg001" "Periplus Scylacis"
 "urn:cts:greekLit:tlg0007.tlg034" "Comparison of Lysander and Sulla"
 "urn:cts:greekLit:tlg0086.tlg018" "De iuventute et senectute, De vita et morte"
 "urn:cts:greekLit:tlg0013.tlg008" "Hymn 8 to Ares"
 "urn:cts:greekLit:tlg4016.tlg002" "In Aristotelis Categorias Commentarius"
 "urn:cts:greekLit:tlg0552.tlg003" "De conoidibus et sphaeroidibus"
 "urn:cts:greekLit:tlg0540.tlg029" "Against Philocrates: Supplementary"
 "urn:cts:greekLit:tlg0086.tlg020" "De longitudine et brevitate vitae"
 "urn:cts:greekLit:tlg4016.tlg001" "In Porphyrii Isagogen Sive Quinque Voces"
 "urn:cts:greekLit:tlg0565.tlg002" "De signis Fracturarum"
 "urn:cts:greekLit:tlg0540.tlg011" "Against Theomnestus 2"
 "urn:cts:greekLit:tlg0552.tlg004" "De lineis spiralibus"
 "urn:cts:greekLit:tlg0007.tlg062" "Comparison of Dion and Brutus"
 "urn:cts:greekLit:tlg0014.tlg015" "For the Liberty of the Rhodians"
 "urn:cts:greekLit:tlg0643.tlg001" "Iatrica"
 "urn:cts:greekLit:tlg0552.tlg007" "Quadratura parabolae"
 "urn:cts:greekLit:tlg0527.tlg041" "Jonas"
 "urn:cts:greekLit:tlg0070.tlg001" "Isidori Characeni Mansiones Parthicae"
 "urn:cts:greekLit:tlg0062.tlg005" "Electrum"
 "urn:cts:greekLit:tlg0552.tlg006" "Arenarius"
 "urn:cts:greekLit:tlg0007.tlg009" "Comparison of Solon and Publicola"
 "urn:cts:greekLit:tlg0643.tlg002" "Anonymus Londinensis Fragmenta"
 "urn:cts:greekLit:tlg0627.tlg047" "De visu"
 "urn:cts:greekLit:tlg0627.tlg039" "De exsectione foetus"
 "urn:cts:greekLit:tlg0628.tlg003" "Epistulae spuriae"
 "urn:cts:greekLit:tlg0361.tlg001" "Introductio Harmonica"
 "urn:cts:greekLit:tlg1799.tlg012" "Phaenomena"
 "urn:cts:greekLit:tlg0013.tlg029" "Hymn 29 to Hestia"
 "urn:cts:greekLit:tlg0552.tlg012" "Problema bovinum"
 "urn:cts:greekLit:tlg0013.tlg009" "Hymn 9 to Artemis"
 "urn:cts:greekLit:tlg0086.tlg008" "De divinatione per somnum"
 "urn:cts:latinLit:phi0474.phi055" "De Officiis"
 "urn:cts:greekLit:tlg0732.tlg003" "De febribus [Sp.]"
 "urn:cts:greekLit:tlg0530.tlg006" "Ad Gaurum quomodo animetur fetus"
 "urn:cts:greekLit:tlg2601.tlg001" "On the figures in Demosthenes"
 "urn:cts:greekLit:tlg0059.tlg016" "Lovers"
 "urn:cts:greekLit:tlg0013.tlg030" "Hymn 30 to Earth"
 "urn:cts:greekLit:tlg0007.tlg053" "Comparison of Agis and Cleomenes and the Gracchi"
 "urn:cts:greekLit:tlg0358.tlg004" "Excerpta"
 "urn:cts:greekLit:tlg0031.tlg024" "2 John"
 "urn:cts:greekLit:tlg0627.tlg040" "De anatomia"
 "urn:cts:greekLit:tlg0062.tlg050" "Deorum concilium"
 "urn:cts:greekLit:tlg0731.tlg001" "Physiognomonica"
 "urn:cts:greekLit:tlg0074.tlg004" "Periplus Ponti Euxini"
 "urn:cts:greekLit:tlg0007.tlg043" "Comparison of Sertorius and Eumenes"
 "urn:cts:greekLit:tlg0555.tlg004" "Stromata Books 7-8"
 "urn:cts:greekLit:tlg0552.tlg008" "De corporibus fluitantibus"
 "urn:cts:greekLit:tlg0013.tlg026" "Hymn 26 To Dionysus"
 "urn:cts:greekLit:tlg0062.tlg004" "Hercules"
 "urn:cts:greekLit:tlg0074.tlg006" "Acies Contra Alanos"
 "urn:cts:greekLit:tlg0059.tlg029" "Cleitophon"
 "urn:cts:greekLit:tlg0540.tlg034" "Against The Subversion of the Ancestral Constitution of Athens"
 "urn:cts:greekLit:tlg0057.tlg034" "De parvae pilae exercitio"
 "urn:cts:greekLit:tlg0013.tlg020" "Hymn 20 To Hephaestus"
 "urn:cts:greekLit:tlg1799.tlg015" "Sectio canonis [Sp.]"
 "urn:cts:greekLit:tlg0062.tlg010" "Patriae encomium"
 "urn:cts:greekLit:tlg2027.tlg001" "Ars rhetorica"
 "urn:cts:greekLit:tlg0559.tlg006" "Metrica"
 "urn:cts:greekLit:tlg0057.tlg081" "Institutio logica"
 "urn:cts:greekLit:tlg0013.tlg022" "Hymn 22 To Poseidon"
 "urn:cts:greekLit:tlg0007.tlg014" "Comparison of Pericles and Fabius Maximus"
 "urn:cts:greekLit:tlg0007.tlg037" "Comparison of Lucullus and Cimon"
 "urn:cts:greekLit:tlg0007.tlg023" "Comparison of Pelopidas and Marcellus"
 "urn:cts:greekLit:tlg0013.tlg018" "Hymn 18 to Hermes"
 "urn:cts:greekLit:tlg0552.tlg002" "Dimensio circuli"
 "urn:cts:greekLit:tlg2036.tlg001" "In Aristotelis Categorias Commentarium"
 "urn:cts:greekLit:tlg1799.tlg007" "Data"
 "urn:cts:latinLit:phi0474.phi045" "Academica"
 "urn:cts:greekLit:tlg4015.tlg006" "In Aristotelis Libros De Generatione Et Corruptione Commentaria"
 "urn:cts:greekLit:tlg0007.tlg046" "Comparison of Agesilaus and Pompey"
 "urn:cts:greekLit:tlg0627.tlg013" "Iusiurandum"
 "urn:cts:greekLit:tlg2001.tlg038" "Analyticorum Posteriorum Paraphrasis"
 "urn:cts:greekLit:tlg0013.tlg028" "Hymn 28 to Athena"
 "urn:cts:greekLit:tlg0527.tlg043" "Habacuc"
 "urn:cts:greekLit:tlg0010.tlg029" "To Antipater"
 "urn:cts:greekLit:tlg0062.tlg006" "Muscae encomium"
 "urn:cts:greekLit:tlg0552.tlg009" "Stomachion"
 "urn:cts:greekLit:tlg2042.tlg001" "Contra Celsum"
 "urn:cts:greekLit:tlg0627.tlg053" "De diebus criticis"
 "urn:cts:greekLit:tlg4019.tlg001" "Prolegomena"
 "urn:cts:greekLit:tlg0010.tlg027" "To Philip, I"
 "urn:cts:greekLit:tlg4020.tlg001" "In Porphyrii Isagogen"
 "urn:cts:greekLit:tlg0057.tlg019" "De Victu Attenuante"
 "urn:cts:greekLit:tlg0057.tlg103" "De consuetudinibus"
 "urn:cts:greekLit:tlg0527.tlg058" "Bel et Draco (translatio Graeca)"
 "urn:cts:greekLit:tlg0527.tlg040" "Abdias"
 "urn:cts:greekLit:tlg4036.tlg023" "Chrestomathy"
 "urn:cts:greekLit:tlg0010.tlg024" "To Archidamus"
 "urn:cts:greekLit:tlg0013.tlg011" "Hymn 11 To Athena"
 "urn:cts:greekLit:tlg0013.tlg024" "Hymn 24 To Hestia"
 "urn:cts:greekLit:tlg0527.tlg044" "Sophonias"
 "urn:cts:greekLit:tlg0013.tlg023" "Hymn 23 to Zeus"
 "urn:cts:greekLit:tlg0527.tlg028" "Odae"
 "urn:cts:greekLit:tlg1389.tlg001" "Lexicon in decem oratores Atticos"
 "urn:cts:greekLit:tlg0551.tlg006" "Sicily and the Other Islands"
 "urn:cts:greekLit:tlg0010.tlg025" "To the Rulers of the Mytilenaeans"
 "urn:cts:greekLit:tlg0013.tlg015" "Hymn 15 To Heracles"
 "urn:cts:greekLit:tlg0057.tlg003" "Quod optimus medicus sit quoque philosophus"
 "urn:cts:greekLit:tlg0013.tlg016" "Hymn 16 To Asclepius"
 "urn:cts:latinLit:phi0474.phi042" "Topica"
 "urn:cts:greekLit:tlg0013.tlg014" "Hymn 14 to the Mother of the Gods"
 "urn:cts:greekLit:tlg0540.tlg005" "For Callias"
 "urn:cts:greekLit:tlg0013.tlg021" "Hymn 21 To Apollo"
 "urn:cts:greekLit:tlg4072.tlg001" "Commentarii in libros de sphaera et cylindro"
 "urn:cts:greekLit:tlg0057.tlg002" "De optima doctrina"
 "urn:cts:greekLit:tlg0551.tlg003" "Italy"
 "urn:cts:greekLit:tlg0077.tlg001" "Stadiasmus Magni Maris"
 "urn:cts:greekLit:tlg0732.tlg001" "De mixtione"
 "urn:cts:greekLit:tlg0013.tlg010" "Hymn 10 to Aphrodite"
 "urn:cts:greekLit:tlg2018.tlg002" "Historia Ecclesiastica"
 "urn:cts:greekLit:tlg0551.tlg002" "Kings"
 "urn:cts:greekLit:tlg4003.tlg003" "Artemidori Geographia (Epitome Marciani)"
 "urn:cts:greekLit:tlg2001.tlg041" "(Sophoniae) In Parva Naturalia Commentarium"
 "urn:cts:greekLit:tlg0010.tlg028" "To Alexander"
 "urn:cts:greekLit:tlg0552.tlg010" "Ad Eratosthenem methodus"
 "urn:cts:greekLit:tlg0069.tlg001" "Descriptio Graeciae"
 "urn:cts:greekLit:tlg0010.tlg030" "To Philip, II"
 "urn:cts:greekLit:tlg0007.tlg029" "Comparison of Philopoemen and Titus"
 "urn:cts:latinLit:phi0474.phi039" "Brutus"
 "urn:cts:greekLit:tlg0013.tlg013" "Hymn 13 to Demeter"
 "urn:cts:greekLit:tlg0606.tlg001" "Ars rhetorica"
 "urn:cts:latinLit:phi0893.phi001" "Carmina"
 "urn:cts:greekLit:tlg0693.tlg001" "Epitome doctrinae Platonicae sive Διδασκαλικός")))

(provide 'hrm-abbr)
